<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>5 Data Manipulation II | HDIS: Analysis of Prosopographical Data–with R</title>
  <meta name="description" content="This is a Handbook for Digital Islamicate Studies. Work in progress, based on tought courses." />
  <meta name="generator" content="bookdown 0.35 and GitBook 2.6.7" />

  <meta property="og:title" content="5 Data Manipulation II | HDIS: Analysis of Prosopographical Data–with R" />
  <meta property="og:type" content="book" />
  
  <meta property="og:description" content="This is a Handbook for Digital Islamicate Studies. Work in progress, based on tought courses." />
  <meta name="github-repo" content="EIS1600/hdis-pua" />

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="5 Data Manipulation II | HDIS: Analysis of Prosopographical Data–with R" />
  
  <meta name="twitter:description" content="This is a Handbook for Digital Islamicate Studies. Work in progress, based on tought courses." />
  

<meta name="author" content="Maxim G. Romanov" />


<meta name="date" content="2023-10-30" />

  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  <link rel="apple-touch-icon-precomposed" sizes="120x120" href="touch-icon.png" />
  <link rel="shortcut icon" href="favicon.ico" type="image/x-icon" />
<link rel="prev" href="data-manipulation-i.html"/>
<link rel="next" href="control-flow-regular-expressions.html"/>
<script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/fuse.js@6.4.6/dist/fuse.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />








<link href="libs/anchor-sections-1.1.0/anchor-sections.css" rel="stylesheet" />
<link href="libs/anchor-sections-1.1.0/anchor-sections-hash.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.1.0/anchor-sections.js"></script>
<script src="libs/htmlwidgets-1.6.2/htmlwidgets.js"></script>
<script src="libs/d3-3.3.8/d3.min.js"></script>
<script src="libs/dagre-0.4.0/dagre-d3.min.js"></script>
<link href="libs/mermaid-0.3.0/dist/mermaid.css" rel="stylesheet" />
<script src="libs/mermaid-0.3.0/dist/mermaid.slim.min.js"></script>
<link href="libs/DiagrammeR-styles-0.2/styles.css" rel="stylesheet" />
<script src="libs/chromatography-0.1/chromatography.js"></script>
<script src="libs/DiagrammeR-binding-1.0.10/DiagrammeR.js"></script>


<style type="text/css">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { color: #008000; } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { color: #008000; font-weight: bold; } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<style type="text/css">
  
  div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
</style>
<style type="text/css">
/* Used with Pandoc 2.11+ new --citeproc when CSL is used */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
}
.hanging div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}
</style>

<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">Handbook of Digital Islamicate Studies</a></li>

<li class="divider"></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i>Preface</a></li>
<li class="chapter" data-level="" data-path="about-the-course.html"><a href="about-the-course.html"><i class="fa fa-check"></i>About the Course</a>
<ul>
<li class="chapter" data-level="" data-path="about-the-course.html"><a href="about-the-course.html#syllabus"><i class="fa fa-check"></i>Syllabus</a>
<ul>
<li class="chapter" data-level="" data-path="about-the-course.html"><a href="about-the-course.html#general-description"><i class="fa fa-check"></i>General Description</a></li>
<li class="chapter" data-level="" data-path="about-the-course.html"><a href="about-the-course.html#learning-objectives"><i class="fa fa-check"></i>Learning objectives</a></li>
<li class="chapter" data-level="" data-path="about-the-course.html"><a href="about-the-course.html#didactic-concept"><i class="fa fa-check"></i>Didactic concept</a></li>
<li class="chapter" data-level="0.0.1" data-path="about-the-course.html"><a href="about-the-course.html#course-structure-and-learning-objectives"><i class="fa fa-check"></i><b>0.0.1</b> Course structure and learning objectives:</a></li>
<li class="chapter" data-level="0.0.2" data-path="about-the-course.html"><a href="about-the-course.html#main-object-of-the-course-pua-dataset"><i class="fa fa-check"></i><b>0.0.2</b> Main Object of the Course: PUA Dataset</a></li>
<li class="chapter" data-level="" data-path="about-the-course.html"><a href="about-the-course.html#course-evaluation-requirements-for-the-full-credit"><i class="fa fa-check"></i>Course Evaluation: requirements for the full credit</a></li>
<li class="chapter" data-level="" data-path="about-the-course.html"><a href="about-the-course.html#class-participation"><i class="fa fa-check"></i>Class Participation</a></li>
<li class="chapter" data-level="" data-path="about-the-course.html"><a href="about-the-course.html#homework"><i class="fa fa-check"></i>Homework</a></li>
<li class="chapter" data-level="" data-path="about-the-course.html"><a href="about-the-course.html#final-project"><i class="fa fa-check"></i>Final Project</a></li>
<li class="chapter" data-level="" data-path="about-the-course.html"><a href="about-the-course.html#additional-study-materials"><i class="fa fa-check"></i>Additional Study Materials</a></li>
<li class="chapter" data-level="" data-path="about-the-course.html"><a href="about-the-course.html#software-tools-technologies"><i class="fa fa-check"></i>Software, Tools, &amp; Technologies:</a></li>
<li class="chapter" data-level="" data-path="about-the-course.html"><a href="about-the-course.html#submitting-homework"><i class="fa fa-check"></i>Submitting Homework:</a></li>
<li class="chapter" data-level="" data-path="about-the-course.html"><a href="about-the-course.html#lesson-topics-subject-to-modifications"><i class="fa fa-check"></i>Lesson Topics (<em>subject to modifications</em>)</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="1" data-path="setting-everything-up.html"><a href="setting-everything-up.html"><i class="fa fa-check"></i><b>1</b> Setting Everything Up</a>
<ul>
<li class="chapter" data-level="1.1" data-path="setting-everything-up.html"><a href="setting-everything-up.html#links-for-things-to-install"><i class="fa fa-check"></i><b>1.1</b> Links for things to install</a></li>
<li class="chapter" data-level="1.2" data-path="setting-everything-up.html"><a href="setting-everything-up.html#setting-things-up"><i class="fa fa-check"></i><b>1.2</b> Setting Things Up</a></li>
<li class="chapter" data-level="1.3" data-path="setting-everything-up.html"><a href="setting-everything-up.html#creating-a-project"><i class="fa fa-check"></i><b>1.3</b> Creating a Project</a></li>
<li class="chapter" data-level="1.4" data-path="setting-everything-up.html"><a href="setting-everything-up.html#homework-assignments"><i class="fa fa-check"></i><b>1.4</b> Homework assignments</a></li>
</ul></li>
<li class="chapter" data-level="2" data-path="rstudio-basic-r-commands-swirl-tutorials.html"><a href="rstudio-basic-r-commands-swirl-tutorials.html"><i class="fa fa-check"></i><b>2</b> RStudio, Basic R Commands, Swirl Tutorials</a>
<ul>
<li class="chapter" data-level="2.1" data-path="rstudio-basic-r-commands-swirl-tutorials.html"><a href="rstudio-basic-r-commands-swirl-tutorials.html#this-chapter"><i class="fa fa-check"></i><b>2.1</b> This Chapter</a></li>
<li class="chapter" data-level="2.2" data-path="rstudio-basic-r-commands-swirl-tutorials.html"><a href="rstudio-basic-r-commands-swirl-tutorials.html#overview-of-r"><i class="fa fa-check"></i><b>2.2</b> Overview of R</a></li>
<li class="chapter" data-level="2.3" data-path="rstudio-basic-r-commands-swirl-tutorials.html"><a href="rstudio-basic-r-commands-swirl-tutorials.html#rstudio-interface"><i class="fa fa-check"></i><b>2.3</b> RStudio Interface</a></li>
<li class="chapter" data-level="2.4" data-path="rstudio-basic-r-commands-swirl-tutorials.html"><a href="rstudio-basic-r-commands-swirl-tutorials.html#main-file-types"><i class="fa fa-check"></i><b>2.4</b> Main File Types</a></li>
<li class="chapter" data-level="2.5" data-path="rstudio-basic-r-commands-swirl-tutorials.html"><a href="rstudio-basic-r-commands-swirl-tutorials.html#projects"><i class="fa fa-check"></i><b>2.5</b> Projects</a></li>
<li class="chapter" data-level="2.6" data-path="rstudio-basic-r-commands-swirl-tutorials.html"><a href="rstudio-basic-r-commands-swirl-tutorials.html#basic-commands"><i class="fa fa-check"></i><b>2.6</b> Basic Commands</a></li>
<li class="chapter" data-level="2.7" data-path="rstudio-basic-r-commands-swirl-tutorials.html"><a href="rstudio-basic-r-commands-swirl-tutorials.html#built-in-functions"><i class="fa fa-check"></i><b>2.7</b> Built-in Functions</a></li>
<li class="chapter" data-level="2.8" data-path="rstudio-basic-r-commands-swirl-tutorials.html"><a href="rstudio-basic-r-commands-swirl-tutorials.html#librariespackages"><i class="fa fa-check"></i><b>2.8</b> Libraries/Packages</a></li>
<li class="chapter" data-level="2.9" data-path="rstudio-basic-r-commands-swirl-tutorials.html"><a href="rstudio-basic-r-commands-swirl-tutorials.html#values-and-their-types"><i class="fa fa-check"></i><b>2.9</b> Values and their types</a></li>
<li class="chapter" data-level="2.10" data-path="rstudio-basic-r-commands-swirl-tutorials.html"><a href="rstudio-basic-r-commands-swirl-tutorials.html#basic-data-structures-and-their-practical-usage"><i class="fa fa-check"></i><b>2.10</b> Basic Data Structures and Their Practical Usage</a>
<ul>
<li class="chapter" data-level="2.10.1" data-path="rstudio-basic-r-commands-swirl-tutorials.html"><a href="rstudio-basic-r-commands-swirl-tutorials.html#basic-data-structures"><i class="fa fa-check"></i><b>2.10.1</b> Basic data structures</a></li>
<li class="chapter" data-level="2.10.2" data-path="rstudio-basic-r-commands-swirl-tutorials.html"><a href="rstudio-basic-r-commands-swirl-tutorials.html#main-properties-of-basic-data-structures"><i class="fa fa-check"></i><b>2.10.2</b> Main properties of basic data structures</a></li>
<li class="chapter" data-level="2.10.3" data-path="rstudio-basic-r-commands-swirl-tutorials.html"><a href="rstudio-basic-r-commands-swirl-tutorials.html#most-common-usage-of-basic-data-structures"><i class="fa fa-check"></i><b>2.10.3</b> Most Common Usage of Basic Data Structures:</a></li>
<li class="chapter" data-level="2.10.4" data-path="rstudio-basic-r-commands-swirl-tutorials.html"><a href="rstudio-basic-r-commands-swirl-tutorials.html#basic-data-structures-examples"><i class="fa fa-check"></i><b>2.10.4</b> Basic Data Structures Examples</a></li>
</ul></li>
<li class="chapter" data-level="2.11" data-path="rstudio-basic-r-commands-swirl-tutorials.html"><a href="rstudio-basic-r-commands-swirl-tutorials.html#homework-with-swirl"><i class="fa fa-check"></i><b>2.11</b> Homework with <code>swirl()</code></a></li>
</ul></li>
<li class="chapter" data-level="3" data-path="r-markdown-and-r-notebooks.html"><a href="r-markdown-and-r-notebooks.html"><i class="fa fa-check"></i><b>3</b> R Markdown and R Notebooks</a>
<ul>
<li class="chapter" data-level="3.1" data-path="r-markdown-and-r-notebooks.html"><a href="r-markdown-and-r-notebooks.html#previous-lesson"><i class="fa fa-check"></i><b>3.1</b> Previous lesson</a></li>
<li class="chapter" data-level="3.2" data-path="r-markdown-and-r-notebooks.html"><a href="r-markdown-and-r-notebooks.html#this-lesson"><i class="fa fa-check"></i><b>3.2</b> This lesson</a></li>
<li class="chapter" data-level="3.3" data-path="r-markdown-and-r-notebooks.html"><a href="r-markdown-and-r-notebooks.html#r-notebookmarkdown"><i class="fa fa-check"></i><b>3.3</b> R Notebook/Markdown</a>
<ul>
<li class="chapter" data-level="3.3.1" data-path="r-markdown-and-r-notebooks.html"><a href="r-markdown-and-r-notebooks.html#r-notebook-yml-header"><i class="fa fa-check"></i><b>3.3.1</b> R Notebook/ YML Header</a></li>
<li class="chapter" data-level="3.3.2" data-path="r-markdown-and-r-notebooks.html"><a href="r-markdown-and-r-notebooks.html#basics-of-markdown"><i class="fa fa-check"></i><b>3.3.2</b> Basics of Markdown</a></li>
</ul></li>
<li class="chapter" data-level="3.4" data-path="r-markdown-and-r-notebooks.html"><a href="r-markdown-and-r-notebooks.html#homework-1"><i class="fa fa-check"></i><b>3.4</b> Homework</a></li>
</ul></li>
<li class="chapter" data-level="4" data-path="data-manipulation-i.html"><a href="data-manipulation-i.html"><i class="fa fa-check"></i><b>4</b> Data Manipulation I</a>
<ul>
<li class="chapter" data-level="4.1" data-path="data-manipulation-i.html"><a href="data-manipulation-i.html#this-chapter-1"><i class="fa fa-check"></i><b>4.1</b> This Chapter</a></li>
<li class="chapter" data-level="4.2" data-path="data-manipulation-i.html"><a href="data-manipulation-i.html#why-tidyverse"><i class="fa fa-check"></i><b>4.2</b> Why <code>tidyverse</code>?</a></li>
<li class="chapter" data-level="4.3" data-path="data-manipulation-i.html"><a href="data-manipulation-i.html#main-data-file-formats-csv-and-tsv"><i class="fa fa-check"></i><b>4.3</b> Main Data File Formats: CSV and TSV</a></li>
<li class="chapter" data-level="4.4" data-path="data-manipulation-i.html"><a href="data-manipulation-i.html#loading-data-into-r"><i class="fa fa-check"></i><b>4.4</b> Loading Data into R</a>
<ul>
<li class="chapter" data-level="4.4.1" data-path="data-manipulation-i.html"><a href="data-manipulation-i.html#loading-csv-and-tsv-files"><i class="fa fa-check"></i><b>4.4.1</b> Loading CSV and TSV files</a></li>
<li class="chapter" data-level="4.4.2" data-path="data-manipulation-i.html"><a href="data-manipulation-i.html#r-specific-data-format-rds"><i class="fa fa-check"></i><b>4.4.2</b> R-specific Data “Format”: RDS</a></li>
</ul></li>
<li class="chapter" data-level="4.5" data-path="data-manipulation-i.html"><a href="data-manipulation-i.html#loading-pua-data"><i class="fa fa-check"></i><b>4.5</b> Loading PUA data</a></li>
<li class="chapter" data-level="4.6" data-path="data-manipulation-i.html"><a href="data-manipulation-i.html#exploring-pua-data"><i class="fa fa-check"></i><b>4.6</b> Exploring PUA Data</a></li>
<li class="chapter" data-level="4.7" data-path="data-manipulation-i.html"><a href="data-manipulation-i.html#main-commands-for-engaging-with-a-tibble"><i class="fa fa-check"></i><b>4.7</b> Main commands for engaging with a tibble</a>
<ul>
<li class="chapter" data-level="4.7.1" data-path="data-manipulation-i.html"><a href="data-manipulation-i.html#chaining-with"><i class="fa fa-check"></i><b>4.7.1</b> Chaining with <code>%&gt;%</code></a></li>
</ul></li>
<li class="chapter" data-level="4.8" data-path="data-manipulation-i.html"><a href="data-manipulation-i.html#important-functions-from-dplyr"><i class="fa fa-check"></i><b>4.8</b> Important Functions from <code>dplyr</code></a></li>
<li class="chapter" data-level="4.9" data-path="data-manipulation-i.html"><a href="data-manipulation-i.html#important-functions-from-tidyr"><i class="fa fa-check"></i><b>4.9</b> Important Functions from <code>tidyr</code></a></li>
<li class="chapter" data-level="4.10" data-path="data-manipulation-i.html"><a href="data-manipulation-i.html#function-usage"><i class="fa fa-check"></i><b>4.10</b> Function usage</a>
<ul>
<li class="chapter" data-level="4.10.1" data-path="data-manipulation-i.html"><a href="data-manipulation-i.html#filter"><i class="fa fa-check"></i><b>4.10.1</b> <code>filter()</code></a></li>
<li class="chapter" data-level="4.10.2" data-path="data-manipulation-i.html"><a href="data-manipulation-i.html#select"><i class="fa fa-check"></i><b>4.10.2</b> <code>select()</code></a></li>
<li class="chapter" data-level="4.10.3" data-path="data-manipulation-i.html"><a href="data-manipulation-i.html#mutate-and-transmute"><i class="fa fa-check"></i><b>4.10.3</b> <code>mutate()</code> and <code>transmute()</code></a></li>
<li class="chapter" data-level="4.10.4" data-path="data-manipulation-i.html"><a href="data-manipulation-i.html#rename"><i class="fa fa-check"></i><b>4.10.4</b> <code>rename()</code></a></li>
<li class="chapter" data-level="4.10.5" data-path="data-manipulation-i.html"><a href="data-manipulation-i.html#arrange"><i class="fa fa-check"></i><b>4.10.5</b> <code>arrange()</code></a></li>
<li class="chapter" data-level="4.10.6" data-path="data-manipulation-i.html"><a href="data-manipulation-i.html#group_by-ungroup"><i class="fa fa-check"></i><b>4.10.6</b> <code>group_by()</code> / <code>ungroup()</code></a></li>
<li class="chapter" data-level="4.10.7" data-path="data-manipulation-i.html"><a href="data-manipulation-i.html#summarise-or-summarize"><i class="fa fa-check"></i><b>4.10.7</b> <code>summarise()</code> or <code>summarize()</code></a></li>
<li class="chapter" data-level="4.10.8" data-path="data-manipulation-i.html"><a href="data-manipulation-i.html#join_-functions"><i class="fa fa-check"></i><b>4.10.8</b> <code>join_*</code> functions</a></li>
<li class="chapter" data-level="4.10.9" data-path="data-manipulation-i.html"><a href="data-manipulation-i.html#pivot_-functions"><i class="fa fa-check"></i><b>4.10.9</b> <code>pivot_*()</code> functions</a></li>
</ul></li>
<li class="chapter" data-level="4.11" data-path="data-manipulation-i.html"><a href="data-manipulation-i.html#homework-tasks"><i class="fa fa-check"></i><b>4.11</b> Homework Tasks</a></li>
<li class="chapter" data-level="4.12" data-path="data-manipulation-i.html"><a href="data-manipulation-i.html#appendix-window-function-in-tidyverse"><i class="fa fa-check"></i><b>4.12</b> Appendix: “Window” function in <code>tidyverse</code></a></li>
</ul></li>
<li class="chapter" data-level="5" data-path="data-manipulation-ii.html"><a href="data-manipulation-ii.html"><i class="fa fa-check"></i><b>5</b> Data Manipulation II</a>
<ul>
<li class="chapter" data-level="5.1" data-path="data-manipulation-ii.html"><a href="data-manipulation-ii.html#this-chapter-2"><i class="fa fa-check"></i><b>5.1</b> This Chapter</a></li>
<li class="chapter" data-level="5.2" data-path="data-manipulation-ii.html"><a href="data-manipulation-ii.html#problems"><i class="fa fa-check"></i><b>5.2</b> Problems</a>
<ul>
<li class="chapter" data-level="5.2.1" data-path="data-manipulation-ii.html"><a href="data-manipulation-ii.html#who-is-the-oldest-individual-we-have-in-the-pua-data"><i class="fa fa-check"></i><b>5.2.1</b> [1] Who is the oldest individual we have in the PUA data?</a></li>
<li class="chapter" data-level="5.2.2" data-path="data-manipulation-ii.html"><a href="data-manipulation-ii.html#which-places-did-this-individual-visit"><i class="fa fa-check"></i><b>5.2.2</b> [2] Which places did this individual visit?</a></li>
<li class="chapter" data-level="5.2.3" data-path="data-manipulation-ii.html"><a href="data-manipulation-ii.html#what-kind-of-activities-was-that-individual-involved-in"><i class="fa fa-check"></i><b>5.2.3</b> [3] What kind of activities was that individual involved in?</a></li>
<li class="chapter" data-level="5.2.4" data-path="data-manipulation-ii.html"><a href="data-manipulation-ii.html#who-is-the-oldest-jurist-faqīh-in-the-pua-data"><i class="fa fa-check"></i><b>5.2.4</b> [4] Who is the oldest jurist (<em>faqīh</em>) in the PUA data?</a></li>
<li class="chapter" data-level="5.2.5" data-path="data-manipulation-ii.html"><a href="data-manipulation-ii.html#can-you-find-a-century-in-which-andalusians-traveled-the-most"><i class="fa fa-check"></i><b>5.2.5</b> [6] Can you find a century in which Andalusians traveled the most?</a></li>
<li class="chapter" data-level="5.2.6" data-path="data-manipulation-ii.html"><a href="data-manipulation-ii.html#what-are-the-10-most-common-activities-andalusians-were-involved-into"><i class="fa fa-check"></i><b>5.2.6</b> [7] What are the 10 most common activities Andalusians were involved into?</a></li>
<li class="chapter" data-level="5.2.7" data-path="data-manipulation-ii.html"><a href="data-manipulation-ii.html#what-are-the-most-common-activities-in-the-5th-ah-century"><i class="fa fa-check"></i><b>5.2.7</b> [8] What are the most common activities in the 5th AH century?</a></li>
<li class="chapter" data-level="5.2.8" data-path="data-manipulation-ii.html"><a href="data-manipulation-ii.html#what-are-the-main-locations-of-the-5-largest-families-places-from-familia"><i class="fa fa-check"></i><b>5.2.8</b> [9] What are the main locations of the 5 largest families? (places from <code>familia</code>)</a></li>
<li class="chapter" data-level="5.2.9" data-path="data-manipulation-ii.html"><a href="data-manipulation-ii.html#what-are-the-most-visited-locations-among-the-members-of-those-families-places-from-personaje_lugar"><i class="fa fa-check"></i><b>5.2.9</b> [10] What are the most visited locations among the members of those families? (places from <code>personaje_lugar</code>)</a></li>
<li class="chapter" data-level="5.2.10" data-path="data-manipulation-ii.html"><a href="data-manipulation-ii.html#in-which-century-do-we-have-the-largest-number-of-families"><i class="fa fa-check"></i><b>5.2.10</b> [11] In which century do we have the largest number of families?</a></li>
<li class="chapter" data-level="5.2.11" data-path="data-manipulation-ii.html"><a href="data-manipulation-ii.html#what-is-the-peak-century-in-the-history-of-al-andalus-this-can-be-measured-by-the-highest-number-of-people."><i class="fa fa-check"></i><b>5.2.11</b> [12] What is the peak century in the history of al-Andalus? (This can be measured by the highest number of people.)</a></li>
<li class="chapter" data-level="5.2.12" data-path="data-manipulation-ii.html"><a href="data-manipulation-ii.html#what-is-the-most-prominent-location-in-al-andalus-in-general-what-about-by-centuries-prominent-means-that-it-has-the-highest-number-of-people-associated-with-it."><i class="fa fa-check"></i><b>5.2.12</b> [13] What is the most prominent location in al-Andalus in general? What about by centuries? (Prominent means that it has the highest number of people associated with it.)</a></li>
<li class="chapter" data-level="5.2.13" data-path="data-manipulation-ii.html"><a href="data-manipulation-ii.html#what-is-the-most-prominent-location-outside-of-al-andalus-what-about-by-centuries"><i class="fa fa-check"></i><b>5.2.13</b> [14] What is the most prominent location outside of al-Andalus? What about by centuries?</a></li>
<li class="chapter" data-level="5.2.14" data-path="data-manipulation-ii.html"><a href="data-manipulation-ii.html#do-the-same-task-but-for-common-era-centuries."><i class="fa fa-check"></i><b>5.2.14</b> [15] Do the same task, but for common era centuries.</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="6" data-path="control-flow-regular-expressions.html"><a href="control-flow-regular-expressions.html"><i class="fa fa-check"></i><b>6</b> Control Flow; Regular Expressions</a>
<ul>
<li class="chapter" data-level="6.1" data-path="control-flow-regular-expressions.html"><a href="control-flow-regular-expressions.html#this-chapter-3"><i class="fa fa-check"></i><b>6.1</b> This Chapter</a></li>
<li class="chapter" data-level="6.2" data-path="control-flow-regular-expressions.html"><a href="control-flow-regular-expressions.html#control-flow"><i class="fa fa-check"></i><b>6.2</b> Control Flow</a>
<ul>
<li class="chapter" data-level="6.2.1" data-path="control-flow-regular-expressions.html"><a href="control-flow-regular-expressions.html#conditional-statements"><i class="fa fa-check"></i><b>6.2.1</b> Conditional statements</a></li>
<li class="chapter" data-level="6.2.2" data-path="control-flow-regular-expressions.html"><a href="control-flow-regular-expressions.html#loops"><i class="fa fa-check"></i><b>6.2.2</b> Loops</a></li>
<li class="chapter" data-level="6.2.3" data-path="control-flow-regular-expressions.html"><a href="control-flow-regular-expressions.html#functions"><i class="fa fa-check"></i><b>6.2.3</b> Functions</a></li>
</ul></li>
<li class="chapter" data-level="6.3" data-path="control-flow-regular-expressions.html"><a href="control-flow-regular-expressions.html#regular-expressions-in-r"><i class="fa fa-check"></i><b>6.3</b> Regular Expressions in R</a>
<ul>
<li class="chapter" data-level="6.3.1" data-path="control-flow-regular-expressions.html"><a href="control-flow-regular-expressions.html#basics-of-regular-expressions"><i class="fa fa-check"></i><b>6.3.1</b> Basics of Regular Expressions</a></li>
<li class="chapter" data-level="6.3.2" data-path="control-flow-regular-expressions.html"><a href="control-flow-regular-expressions.html#regular-expressions-in-r-1"><i class="fa fa-check"></i><b>6.3.2</b> Regular Expressions in R</a></li>
<li class="chapter" data-level="6.3.3" data-path="control-flow-regular-expressions.html"><a href="control-flow-regular-expressions.html#tips-for-regular-expressions-in-r"><i class="fa fa-check"></i><b>6.3.3</b> Tips for Regular Expressions in R</a></li>
<li class="chapter" data-level="6.3.4" data-path="control-flow-regular-expressions.html"><a href="control-flow-regular-expressions.html#in-class-practice"><i class="fa fa-check"></i><b>6.3.4</b> In-Class Practice</a></li>
<li class="chapter" data-level="6.3.5" data-path="control-flow-regular-expressions.html"><a href="control-flow-regular-expressions.html#the-practice-regex-file"><i class="fa fa-check"></i><b>6.3.5</b> The Practice Regex File</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="7" data-path="getting-your-data-right.html"><a href="getting-your-data-right.html"><i class="fa fa-check"></i><b>7</b> Getting Your Data Right</a>
<ul>
<li class="chapter" data-level="7.1" data-path="getting-your-data-right.html"><a href="getting-your-data-right.html#this-chapter-4"><i class="fa fa-check"></i><b>7.1</b> This Chapter</a></li>
<li class="chapter" data-level="7.2" data-path="getting-your-data-right.html"><a href="getting-your-data-right.html#getting-your-own-data"><i class="fa fa-check"></i><b>7.2</b> 1. Getting your own data</a>
<ul>
<li class="chapter" data-level="7.2.1" data-path="getting-your-data-right.html"><a href="getting-your-data-right.html#ways-of-obtaining-data"><i class="fa fa-check"></i><b>7.2.1</b> Ways of obtaining data</a></li>
<li class="chapter" data-level="7.2.2" data-path="getting-your-data-right.html"><a href="getting-your-data-right.html#major-formats"><i class="fa fa-check"></i><b>7.2.2</b> Major formats</a></li>
<li class="chapter" data-level="7.2.3" data-path="getting-your-data-right.html"><a href="getting-your-data-right.html#ways-of-obtaining-data-1"><i class="fa fa-check"></i><b>7.2.3</b> Ways of obtaining data</a></li>
<li class="chapter" data-level="7.2.4" data-path="getting-your-data-right.html"><a href="getting-your-data-right.html#major-formats-1"><i class="fa fa-check"></i><b>7.2.4</b> Major formats</a></li>
</ul></li>
<li class="chapter" data-level="7.3" data-path="getting-your-data-right.html"><a href="getting-your-data-right.html#tidying-data"><i class="fa fa-check"></i><b>7.3</b> 2. Tidying Data</a>
<ul>
<li class="chapter" data-level="7.3.1" data-path="getting-your-data-right.html"><a href="getting-your-data-right.html#basic-principles-of-organizing-data-tidy-data"><i class="fa fa-check"></i><b>7.3.1</b> Basic principles of organizing data: <em>Tidy Data</em></a></li>
<li class="chapter" data-level="7.3.2" data-path="getting-your-data-right.html"><a href="getting-your-data-right.html#clean-data-tidy-data-additional-explanations"><i class="fa fa-check"></i><b>7.3.2</b> Clean Data / Tidy Data: <em>additional explanations</em></a></li>
<li class="chapter" data-level="7.3.3" data-path="getting-your-data-right.html"><a href="getting-your-data-right.html#discussion-a-bulliet-dataset"><i class="fa fa-check"></i><b>7.3.3</b> <em>Discussion</em>: “A Bulliet Dataset”</a></li>
</ul></li>
<li class="chapter" data-level="7.4" data-path="getting-your-data-right.html"><a href="getting-your-data-right.html#modeling-data"><i class="fa fa-check"></i><b>7.4</b> 3. Modeling Data</a>
<ul>
<li class="chapter" data-level="7.4.1" data-path="getting-your-data-right.html"><a href="getting-your-data-right.html#categorization-as-a-way-of-modeling-data"><i class="fa fa-check"></i><b>7.4.1</b> Categorization as a Way of modeling data</a></li>
<li class="chapter" data-level="7.4.2" data-path="getting-your-data-right.html"><a href="getting-your-data-right.html#normalization"><i class="fa fa-check"></i><b>7.4.2</b> Normalization</a></li>
<li class="chapter" data-level="7.4.3" data-path="getting-your-data-right.html"><a href="getting-your-data-right.html#note-proxies-features-abstractions"><i class="fa fa-check"></i><b>7.4.3</b> Note: <em>Proxies</em>, <em>Features</em>, <em>Abstractions</em></a></li>
</ul></li>
<li class="chapter" data-level="7.5" data-path="getting-your-data-right.html"><a href="getting-your-data-right.html#appendix-ocr-with-r"><i class="fa fa-check"></i><b>7.5</b> Appendix: OCR with R</a></li>
</ul></li>
<li class="chapter" data-level="8" data-path="deep-look-into-the-pua-dataset.html"><a href="deep-look-into-the-pua-dataset.html"><i class="fa fa-check"></i><b>8</b> Deep Look into the PUA Dataset</a>
<ul>
<li class="chapter" data-level="8.1" data-path="deep-look-into-the-pua-dataset.html"><a href="deep-look-into-the-pua-dataset.html#updated-pua-dataset"><i class="fa fa-check"></i><b>8.1</b> Updated PUA Dataset</a></li>
<li class="chapter" data-level="8.2" data-path="deep-look-into-the-pua-dataset.html"><a href="deep-look-into-the-pua-dataset.html#normalized-and-improved-pua-dataset"><i class="fa fa-check"></i><b>8.2</b> Normalized and Improved PUA Dataset</a></li>
<li class="chapter" data-level="8.3" data-path="deep-look-into-the-pua-dataset.html"><a href="deep-look-into-the-pua-dataset.html#modeling-pua-dataset"><i class="fa fa-check"></i><b>8.3</b> Modeling PUA Dataset</a></li>
<li class="chapter" data-level="8.4" data-path="deep-look-into-the-pua-dataset.html"><a href="deep-look-into-the-pua-dataset.html#conceptual-models-for-your-data"><i class="fa fa-check"></i><b>8.4</b> Conceptual Models for Your Data</a></li>
<li class="chapter" data-level="8.5" data-path="deep-look-into-the-pua-dataset.html"><a href="deep-look-into-the-pua-dataset.html#implementation"><i class="fa fa-check"></i><b>8.5</b> Implementation</a></li>
<li class="chapter" data-level="8.6" data-path="deep-look-into-the-pua-dataset.html"><a href="deep-look-into-the-pua-dataset.html#homework-assignment"><i class="fa fa-check"></i><b>8.6</b> Homework assignment</a></li>
<li class="chapter" data-level="8.7" data-path="deep-look-into-the-pua-dataset.html"><a href="deep-look-into-the-pua-dataset.html#reference-materials"><i class="fa fa-check"></i><b>8.7</b> Reference Materials</a></li>
<li class="chapter" data-level="8.8" data-path="deep-look-into-the-pua-dataset.html"><a href="deep-look-into-the-pua-dataset.html#appendix-1-pua-data-tables"><i class="fa fa-check"></i><b>8.8</b> Appendix 1: PUA Data Tables</a>
<ul>
<li class="chapter" data-level="8.8.1" data-path="deep-look-into-the-pua-dataset.html"><a href="deep-look-into-the-pua-dataset.html#main-table"><i class="fa fa-check"></i><b>8.8.1</b> Main Table</a></li>
<li class="chapter" data-level="8.8.2" data-path="deep-look-into-the-pua-dataset.html"><a href="deep-look-into-the-pua-dataset.html#connection-tables"><i class="fa fa-check"></i><b>8.8.2</b> Connection Tables</a></li>
<li class="chapter" data-level="8.8.3" data-path="deep-look-into-the-pua-dataset.html"><a href="deep-look-into-the-pua-dataset.html#auxiliary-tables"><i class="fa fa-check"></i><b>8.8.3</b> Auxiliary Tables</a></li>
<li class="chapter" data-level="8.8.4" data-path="deep-look-into-the-pua-dataset.html"><a href="deep-look-into-the-pua-dataset.html#metadata-tables"><i class="fa fa-check"></i><b>8.8.4</b> Metadata Tables</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="9" data-path="visualizations-plot-and-ggplot.html"><a href="visualizations-plot-and-ggplot.html"><i class="fa fa-check"></i><b>9</b> Visualizations: <code>plot()</code> and <code>ggplot()</code></a>
<ul>
<li class="chapter" data-level="9.1" data-path="visualizations-plot-and-ggplot.html"><a href="visualizations-plot-and-ggplot.html#this-chapter-5"><i class="fa fa-check"></i><b>9.1</b> This Chapter</a></li>
<li class="chapter" data-level="9.2" data-path="visualizations-plot-and-ggplot.html"><a href="visualizations-plot-and-ggplot.html#conceptual-issues"><i class="fa fa-check"></i><b>9.2</b> Conceptual Issues</a>
<ul>
<li class="chapter" data-level="9.2.1" data-path="visualizations-plot-and-ggplot.html"><a href="visualizations-plot-and-ggplot.html#perception"><i class="fa fa-check"></i><b>9.2.1</b> Perception</a></li>
<li class="chapter" data-level="9.2.2" data-path="visualizations-plot-and-ggplot.html"><a href="visualizations-plot-and-ggplot.html#the-rules-of-thumb-for-visualizations"><i class="fa fa-check"></i><b>9.2.2</b> The Rules of Thumb for Visualizations</a></li>
<li class="chapter" data-level="9.2.3" data-path="visualizations-plot-and-ggplot.html"><a href="visualizations-plot-and-ggplot.html#types-of-graphs-and-when-to-use-them"><i class="fa fa-check"></i><b>9.2.3</b> Types of Graphs and When to Use Them</a></li>
</ul></li>
<li class="chapter" data-level="9.3" data-path="visualizations-plot-and-ggplot.html"><a href="visualizations-plot-and-ggplot.html#r-built-in-graphics-functions-quick-overview"><i class="fa fa-check"></i><b>9.3</b> R Built-in Graphics Functions: Quick Overview</a></li>
<li class="chapter" data-level="9.4" data-path="visualizations-plot-and-ggplot.html"><a href="visualizations-plot-and-ggplot.html#tidyverse-graphs-ggplot2"><i class="fa fa-check"></i><b>9.4</b> <code>Tidyverse</code> Graphs: <code>ggplot2</code></a>
<ul>
<li class="chapter" data-level="9.4.1" data-path="visualizations-plot-and-ggplot.html"><a href="visualizations-plot-and-ggplot.html#grammar-of-graphics"><i class="fa fa-check"></i><b>9.4.1</b> Grammar of Graphics</a></li>
<li class="chapter" data-level="9.4.2" data-path="visualizations-plot-and-ggplot.html"><a href="visualizations-plot-and-ggplot.html#code-breakdown"><i class="fa fa-check"></i><b>9.4.2</b> Code Breakdown</a></li>
</ul></li>
<li class="chapter" data-level="9.5" data-path="visualizations-plot-and-ggplot.html"><a href="visualizations-plot-and-ggplot.html#simpler-graphs"><i class="fa fa-check"></i><b>9.5</b> Simpler graphs</a></li>
<li class="chapter" data-level="9.6" data-path="visualizations-plot-and-ggplot.html"><a href="visualizations-plot-and-ggplot.html#other-types-of-graphs"><i class="fa fa-check"></i><b>9.6</b> Other types of graphs</a>
<ul>
<li class="chapter" data-level="9.6.1" data-path="visualizations-plot-and-ggplot.html"><a href="visualizations-plot-and-ggplot.html#scatter-plots"><i class="fa fa-check"></i><b>9.6.1</b> 1. Scatter plots</a></li>
<li class="chapter" data-level="9.6.2" data-path="visualizations-plot-and-ggplot.html"><a href="visualizations-plot-and-ggplot.html#line-charts"><i class="fa fa-check"></i><b>9.6.2</b> 2. Line charts</a></li>
<li class="chapter" data-level="9.6.3" data-path="visualizations-plot-and-ggplot.html"><a href="visualizations-plot-and-ggplot.html#bar-charts"><i class="fa fa-check"></i><b>9.6.3</b> 3. Bar charts</a></li>
<li class="chapter" data-level="9.6.4" data-path="visualizations-plot-and-ggplot.html"><a href="visualizations-plot-and-ggplot.html#histograms"><i class="fa fa-check"></i><b>9.6.4</b> 4. Histograms</a></li>
<li class="chapter" data-level="9.6.5" data-path="visualizations-plot-and-ggplot.html"><a href="visualizations-plot-and-ggplot.html#wordclouds"><i class="fa fa-check"></i><b>9.6.5</b> 5. Wordclouds</a></li>
</ul></li>
<li class="chapter" data-level="9.7" data-path="visualizations-plot-and-ggplot.html"><a href="visualizations-plot-and-ggplot.html#homework-assignment-1"><i class="fa fa-check"></i><b>9.7</b> Homework assignment</a></li>
<li class="chapter" data-level="9.8" data-path="visualizations-plot-and-ggplot.html"><a href="visualizations-plot-and-ggplot.html#appendices"><i class="fa fa-check"></i><b>9.8</b> Appendices</a>
<ul>
<li class="chapter" data-level="9.8.1" data-path="visualizations-plot-and-ggplot.html"><a href="visualizations-plot-and-ggplot.html#appendix-1-when-a-simple-table-may-suffice"><i class="fa fa-check"></i><b>9.8.1</b> Appendix 1: When a “Simple” Table May Suffice</a></li>
</ul></li>
<li class="chapter" data-level="9.9" data-path="visualizations-plot-and-ggplot.html"><a href="visualizations-plot-and-ggplot.html#appendix-interactive-graphs"><i class="fa fa-check"></i><b>9.9</b> Appendix: Interactive Graphs</a>
<ul>
<li class="chapter" data-level="9.9.1" data-path="visualizations-plot-and-ggplot.html"><a href="visualizations-plot-and-ggplot.html#appendix-checklist-for-creating-visualizations"><i class="fa fa-check"></i><b>9.9.1</b> Appendix: Checklist for Creating Visualizations</a></li>
</ul></li>
<li class="chapter" data-level="9.10" data-path="visualizations-plot-and-ggplot.html"><a href="visualizations-plot-and-ggplot.html#appendix-scientific-notation"><i class="fa fa-check"></i><b>9.10</b> Appendix: Scientific Notation</a></li>
<li class="chapter" data-level="9.11" data-path="visualizations-plot-and-ggplot.html"><a href="visualizations-plot-and-ggplot.html#homework-solutions-partial"><i class="fa fa-check"></i><b>9.11</b> Homework solutions (partial)</a>
<ul>
<li class="chapter" data-level="9.11.1" data-path="visualizations-plot-and-ggplot.html"><a href="visualizations-plot-and-ggplot.html#line-charts-1"><i class="fa fa-check"></i><b>9.11.1</b> Line charts</a></li>
<li class="chapter" data-level="9.11.2" data-path="visualizations-plot-and-ggplot.html"><a href="visualizations-plot-and-ggplot.html#bar-charts-1"><i class="fa fa-check"></i><b>9.11.2</b> 3. Bar charts</a></li>
<li class="chapter" data-level="9.11.3" data-path="visualizations-plot-and-ggplot.html"><a href="visualizations-plot-and-ggplot.html#histograms-1"><i class="fa fa-check"></i><b>9.11.3</b> 4. Histograms</a></li>
<li class="chapter" data-level="9.11.4" data-path="visualizations-plot-and-ggplot.html"><a href="visualizations-plot-and-ggplot.html#wordclouds---homework"><i class="fa fa-check"></i><b>9.11.4</b> 5. Wordclouds - Homework</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="10" data-path="overview-of-the-pua-dataset.html"><a href="overview-of-the-pua-dataset.html"><i class="fa fa-check"></i><b>10</b> Overview of the PUA dataset</a>
<ul>
<li class="chapter" data-level="10.1" data-path="overview-of-the-pua-dataset.html"><a href="overview-of-the-pua-dataset.html#the-initial-sql-database-extraction-of-tables"><i class="fa fa-check"></i><b>10.1</b> The initial SQL Database: extraction of tables</a></li>
<li class="chapter" data-level="10.2" data-path="overview-of-the-pua-dataset.html"><a href="overview-of-the-pua-dataset.html#extracting-tables-with-r"><i class="fa fa-check"></i><b>10.2</b> Extracting tables with R</a>
<ul>
<li class="chapter" data-level="10.2.1" data-path="overview-of-the-pua-dataset.html"><a href="overview-of-the-pua-dataset.html#looking-at-the-data"><i class="fa fa-check"></i><b>10.2.1</b> Looking at the data</a></li>
<li class="chapter" data-level="10.2.2" data-path="overview-of-the-pua-dataset.html"><a href="overview-of-the-pua-dataset.html#reorganization-conceptual-model-for-your-data"><i class="fa fa-check"></i><b>10.2.2</b> Reorganization: Conceptual Model For Your Data</a></li>
<li class="chapter" data-level="10.2.3" data-path="overview-of-the-pua-dataset.html"><a href="overview-of-the-pua-dataset.html#improving-pua-data"><i class="fa fa-check"></i><b>10.2.3</b> Improving PUA Data</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="11" data-path="understanding-geographical-maps.html"><a href="understanding-geographical-maps.html"><i class="fa fa-check"></i><b>11</b> Understanding Geographical Maps</a>
<ul>
<li class="chapter" data-level="11.1" data-path="understanding-geographical-maps.html"><a href="understanding-geographical-maps.html#creating-base-maps"><i class="fa fa-check"></i><b>11.1</b> Creating Base Maps</a></li>
<li class="chapter" data-level="11.2" data-path="understanding-geographical-maps.html"><a href="understanding-geographical-maps.html#core-concepts-and-their-practical-implementations"><i class="fa fa-check"></i><b>11.2</b> Core concepts and their practical implementations</a>
<ul>
<li class="chapter" data-level="11.2.1" data-path="understanding-geographical-maps.html"><a href="understanding-geographical-maps.html#projection-issues"><i class="fa fa-check"></i><b>11.2.1</b> Projection Issues</a></li>
<li class="chapter" data-level="11.2.2" data-path="understanding-geographical-maps.html"><a href="understanding-geographical-maps.html#a-digital-map-layers-of-goodness"><i class="fa fa-check"></i><b>11.2.2</b> A Digital Map: Layers of Goodness</a></li>
</ul></li>
<li class="chapter" data-level="11.3" data-path="understanding-geographical-maps.html"><a href="understanding-geographical-maps.html#main-types-of-data-points-lines-polygons"><i class="fa fa-check"></i><b>11.3</b> Main Types of Data: Points, Lines, Polygons</a></li>
<li class="chapter" data-level="11.4" data-path="understanding-geographical-maps.html"><a href="understanding-geographical-maps.html#base-maps"><i class="fa fa-check"></i><b>11.4</b> Base maps</a>
<ul>
<li class="chapter" data-level="11.4.1" data-path="understanding-geographical-maps.html"><a href="understanding-geographical-maps.html#new-libraries"><i class="fa fa-check"></i><b>11.4.1</b> New libraries</a></li>
<li class="chapter" data-level="11.4.2" data-path="understanding-geographical-maps.html"><a href="understanding-geographical-maps.html#compiling-the-base-map"><i class="fa fa-check"></i><b>11.4.2</b> Compiling the base map</a></li>
<li class="chapter" data-level="11.4.3" data-path="understanding-geographical-maps.html"><a href="understanding-geographical-maps.html#adding-data"><i class="fa fa-check"></i><b>11.4.3</b> Adding data</a></li>
</ul></li>
<li class="chapter" data-level="11.5" data-path="understanding-geographical-maps.html"><a href="understanding-geographical-maps.html#reusable-base-map-for-al-andalus"><i class="fa fa-check"></i><b>11.5</b> Reusable Base Map for al-Andalus</a></li>
<li class="chapter" data-level="11.6" data-path="understanding-geographical-maps.html"><a href="understanding-geographical-maps.html#raster-base-maps"><i class="fa fa-check"></i><b>11.6</b> Raster base maps</a></li>
<li class="chapter" data-level="11.7" data-path="understanding-geographical-maps.html"><a href="understanding-geographical-maps.html#homework-2"><i class="fa fa-check"></i><b>11.7</b> Homework</a></li>
</ul></li>
<li class="chapter" data-level="12" data-path="modeling-complex-entities.html"><a href="modeling-complex-entities.html"><i class="fa fa-check"></i><b>12</b> Modeling Complex Entities</a>
<ul>
<li class="chapter" data-level="12.1" data-path="modeling-complex-entities.html"><a href="modeling-complex-entities.html#modeling-regions"><i class="fa fa-check"></i><b>12.1</b> Modeling Regions</a></li>
<li class="chapter" data-level="12.2" data-path="modeling-complex-entities.html"><a href="modeling-complex-entities.html#modeling-periods"><i class="fa fa-check"></i><b>12.2</b> Modeling Periods</a>
<ul>
<li class="chapter" data-level="12.2.1" data-path="modeling-complex-entities.html"><a href="modeling-complex-entities.html#a-1000-and-1-tries"><i class="fa fa-check"></i><b>12.2.1</b> A 1000 And 1 Tries</a></li>
</ul></li>
<li class="chapter" data-level="12.3" data-path="modeling-complex-entities.html"><a href="modeling-complex-entities.html#intermediate-summary"><i class="fa fa-check"></i><b>12.3</b> Intermediate Summary</a></li>
</ul></li>
<li class="chapter" data-level="13" data-path="chronological-cartograpms.html"><a href="chronological-cartograpms.html"><i class="fa fa-check"></i><b>13</b> Chronological Cartograpms</a>
<ul>
<li class="chapter" data-level="13.0.1" data-path="chronological-cartograpms.html"><a href="chronological-cartograpms.html#animated-map-approach"><i class="fa fa-check"></i><b>13.0.1</b> Animated Map Approach</a></li>
<li class="chapter" data-level="13.0.2" data-path="chronological-cartograpms.html"><a href="chronological-cartograpms.html#frame-by-frame-approach"><i class="fa fa-check"></i><b>13.0.2</b> “Frame-by-Frame” Approach</a></li>
<li class="chapter" data-level="13.1" data-path="chronological-cartograpms.html"><a href="chronological-cartograpms.html#chrono-geographical-information-without-maps"><i class="fa fa-check"></i><b>13.1</b> Chrono-Geographical Information without Maps</a></li>
</ul></li>
<li class="chapter" data-level="14" data-path="geographical-networks.html"><a href="geographical-networks.html"><i class="fa fa-check"></i><b>14</b> Geographical Networks</a></li>
<li class="chapter" data-level="15" data-path="social-networks.html"><a href="social-networks.html"><i class="fa fa-check"></i><b>15</b> Social Networks</a></li>
<li class="chapter" data-level="16" data-path="glossary-of-computer-terms.html"><a href="glossary-of-computer-terms.html"><i class="fa fa-check"></i><b>16</b> Glossary of Computer Terms</a>
<ul>
<li class="chapter" data-level="16.1" data-path="glossary-of-computer-terms.html"><a href="glossary-of-computer-terms.html#general-computer-terms"><i class="fa fa-check"></i><b>16.1</b> General Computer Terms</a></li>
<li class="chapter" data-level="16.2" data-path="glossary-of-computer-terms.html"><a href="glossary-of-computer-terms.html#r-specific-terms"><i class="fa fa-check"></i><b>16.2</b> R-Specific Terms</a></li>
<li class="chapter" data-level="16.3" data-path="glossary-of-computer-terms.html"><a href="glossary-of-computer-terms.html#nlp-and-linguistics"><i class="fa fa-check"></i><b>16.3</b> NLP and Linguistics</a></li>
<li class="chapter" data-level="16.4" data-path="glossary-of-computer-terms.html"><a href="glossary-of-computer-terms.html#machine-learning"><i class="fa fa-check"></i><b>16.4</b> Machine Learning</a></li>
</ul></li>
<li class="chapter" data-level="17" data-path="appendices-1.html"><a href="appendices-1.html"><i class="fa fa-check"></i><b>17</b> Appendices</a>
<ul>
<li class="chapter" data-level="17.1" data-path="appendices-1.html"><a href="appendices-1.html#appendix-i-importance-of-basic-computer-skills-for-humanists"><i class="fa fa-check"></i><b>17.1</b> Appendix I: Importance of basic computer skills for humanists</a>
<ul>
<li class="chapter" data-level="17.1.1" data-path="appendices-1.html"><a href="appendices-1.html#importance-of-basic-computer-skills-for-humanists"><i class="fa fa-check"></i><b>17.1.1</b> Importance of basic computer skills for humanists</a></li>
<li class="chapter" data-level="17.1.2" data-path="appendices-1.html"><a href="appendices-1.html#access-to-information"><i class="fa fa-check"></i><b>17.1.2</b> Access to information</a></li>
<li class="chapter" data-level="17.1.3" data-path="appendices-1.html"><a href="appendices-1.html#organization-and-management-of-research-material"><i class="fa fa-check"></i><b>17.1.3</b> Organization and management of research material</a></li>
<li class="chapter" data-level="17.1.4" data-path="appendices-1.html"><a href="appendices-1.html#file-organization"><i class="fa fa-check"></i><b>17.1.4</b> File Organization</a></li>
<li class="chapter" data-level="17.1.5" data-path="appendices-1.html"><a href="appendices-1.html#finding-your-way-around-the-computer"><i class="fa fa-check"></i><b>17.1.5</b> Finding your way around the computer</a></li>
<li class="chapter" data-level="17.1.6" data-path="appendices-1.html"><a href="appendices-1.html#common-file-formats-and-extensions"><i class="fa fa-check"></i><b>17.1.6</b> Common file formats and extensions</a></li>
<li class="chapter" data-level="17.1.7" data-path="appendices-1.html"><a href="appendices-1.html#organizing-files-and-folders-for-research-projects"><i class="fa fa-check"></i><b>17.1.7</b> Organizing files and folders for research projects</a></li>
<li class="chapter" data-level="17.1.8" data-path="appendices-1.html"><a href="appendices-1.html#demonstration-of-file-navigation-using-a-file-explorer-windows-or-finder-mac"><i class="fa fa-check"></i><b>17.1.8</b> Demonstration of file navigation using a file explorer (Windows) or Finder (Mac)</a></li>
<li class="chapter" data-level="17.1.9" data-path="appendices-1.html"><a href="appendices-1.html#command-line-basics"><i class="fa fa-check"></i><b>17.1.9</b> Command Line Basics</a></li>
<li class="chapter" data-level="17.1.10" data-path="appendices-1.html"><a href="appendices-1.html#introduction-to-command-line-interfaces"><i class="fa fa-check"></i><b>17.1.10</b> Introduction to command line interfaces</a></li>
<li class="chapter" data-level="17.1.11" data-path="appendices-1.html"><a href="appendices-1.html#command-line-basic-commands"><i class="fa fa-check"></i><b>17.1.11</b> Command Line: Basic Commands</a></li>
<li class="chapter" data-level="17.1.12" data-path="appendices-1.html"><a href="appendices-1.html#creating-moving-renaming-and-deleting-files-and-folders"><i class="fa fa-check"></i><b>17.1.12</b> Creating, moving, renaming, and deleting files and folders</a></li>
<li class="chapter" data-level="17.1.13" data-path="appendices-1.html"><a href="appendices-1.html#tips-for-efficient-command-line-usage"><i class="fa fa-check"></i><b>17.1.13</b> Tips for efficient command line usage</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="18" data-path="bibliography.html"><a href="bibliography.html"><i class="fa fa-check"></i><b>18</b> Bibliography</a></li>
<li class="divider"></li>
<li><a href="https://github.com/rstudio/bookdown" target="blank">Published with bookdown</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">HDIS: Analysis of Prosopographical Data–with R</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="data-manipulation-ii" class="section level1 hasAnchor" number="5">
<h1><span class="header-section-number">5</span> Data Manipulation II<a href="data-manipulation-ii.html#data-manipulation-ii" class="anchor-section" aria-label="Anchor link to header"></a></h1>
<div id="this-chapter-2" class="section level2 hasAnchor" number="5.1">
<h2><span class="header-section-number">5.1</span> This Chapter<a href="data-manipulation-ii.html#this-chapter-2" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<ul>
<li>we will go over the solutions to the problems from the previous Chapter</li>
</ul>
</div>
<div id="problems" class="section level2 hasAnchor" number="5.2">
<h2><span class="header-section-number">5.2</span> Problems<a href="data-manipulation-ii.html#problems" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Your homework task is to create a notebook for this lesson. For part I, rerun all the code from this lesson in your notebook to make sure it works and you are gaining some understanding of how it works; for the second part, give solutions to all the problems that are given below. Your code chunks should print the answer that comes from your calculations and manipulations. After your code chunk provide a human-readable answer — one or two sentences is sufficient.</p>
<p>Below you will find solutions to the first few problems.</p>
<div id="who-is-the-oldest-individual-we-have-in-the-pua-data" class="section level3 hasAnchor" number="5.2.1">
<h3><span class="header-section-number">5.2.1</span> [1] Who is the oldest individual we have in the PUA data?<a href="data-manipulation-ii.html#who-is-the-oldest-individual-we-have-in-the-pua-data" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<ul>
<li><em>algorithmic solution</em>: we need to find a person with the highest value in the column where ages are recorded;</li>
<li><em>complete solution</em>: we need to find a person with the highest value in column <code>edad</code> in the table <code>personaje</code>; the easiest way will be to use <code>top_n</code> function (<code>top_n(1, wt = edad)</code>);</li>
</ul>
<div class="sourceCode" id="cb58"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb58-1"><a href="data-manipulation-ii.html#cb58-1" tabindex="-1"></a>oldest <span class="ot">&lt;-</span> PUA<span class="sc">$</span>personaje <span class="sc">%&gt;%</span></span>
<span id="cb58-2"><a href="data-manipulation-ii.html#cb58-2" tabindex="-1"></a>  <span class="fu">top_n</span>(<span class="dv">1</span>, <span class="at">wt =</span> edad)</span>
<span id="cb58-3"><a href="data-manipulation-ii.html#cb58-3" tabindex="-1"></a></span>
<span id="cb58-4"><a href="data-manipulation-ii.html#cb58-4" tabindex="-1"></a>oldest</span></code></pre></div>
<pre><code>## # A tibble: 1 × 19
##   idPersonaje idFamilia nombreA     nombreE suhra nacimiento nacimiento_comentario muerte muerte_comentario  edad
##         &lt;dbl&gt;     &lt;dbl&gt; &lt;chr&gt;       &lt;chr&gt;   &lt;chr&gt;      &lt;dbl&gt; &lt;chr&gt;                  &lt;dbl&gt; &lt;chr&gt;             &lt;dbl&gt;
## 1        2455        44 صباح (الصب… Ṣabbāḥ… &lt;NA&gt;         190 ded.                     295 /10 muḥarram 294…   118
## # ℹ 9 more variables: edad_comentario &lt;chr&gt;, resumenBiografico &lt;chr&gt;, creado &lt;dttm&gt;, modificado &lt;dttm&gt;,
## #   publicado &lt;dbl&gt;, maestrosOrientales &lt;chr&gt;, nacimientoec &lt;dbl&gt;, muerteec &lt;dbl&gt;, fuentesCitadas &lt;chr&gt;</code></pre>
<ul>
<li><em>human readable solution, based on results</em>:</li>
</ul>
<div class="sourceCode" id="cb60"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb60-1"><a href="data-manipulation-ii.html#cb60-1" tabindex="-1"></a>The oldest person <span class="cf">in</span> the PUA database is<span class="sc">:</span> <span class="st">`</span><span class="at">r oldest$nombreE</span><span class="st">`</span>.</span>
<span id="cb60-2"><a href="data-manipulation-ii.html#cb60-2" tabindex="-1"></a>His Arabic name is<span class="sc">:</span> <span class="st">``</span>r oldest<span class="sc">$</span>nombreA<span class="st">``</span>. He died at the age</span>
<span id="cb60-3"><a href="data-manipulation-ii.html#cb60-3" tabindex="-1"></a>of <span class="st">`</span><span class="at">r oldest$edad</span><span class="st">`</span> <span class="cf">in</span> <span class="st">`</span><span class="at">r oldest$muerte</span><span class="st">`</span> AH <span class="sc">/</span> <span class="st">`</span><span class="at">r oldest$muerteec</span><span class="st">`</span> CE.</span></code></pre></div>
<p>This solution will be rendered in the notebook as:</p>
<blockquote>
<p>The oldest person in the PUA database is: Ṣabbāḥ / al-Ṣabbāḥ b. ʿAbd al-Raḥmān b. al-Faḍl (b. ʿAmāra) b. ʿAmīra b. Rāšid b. ʿAbd Allāh b. Saʿīd b. Šarīk b. ʿAbd Allāh b. Muslim b. Nawfal b. Rabīʿa b. Mālik b. ʿAtīq b. Malkān b. Kināna al-Kinānī, al ʿUtaqī, Abū l-Guṣn (Abū l-Faḍl). His Arabic name is: <code>صباح (الصباح) بن عبد الرحمن بن الفضل (بن عمارة) بن عميرة بن راشد بن عبد الله بن سعيد بن شريك بن عبد الله بن مسلم بن نوفل بن ربيعة بن مالك بن عتيق بن ملكان بن كنانة الكناني العتقي، أبو الغصن (أبو الفضل).</code> He died at the age of 118 in 295 AH / 907 CE.</p>
</blockquote>
</div>
<div id="which-places-did-this-individual-visit" class="section level3 hasAnchor" number="5.2.2">
<h3><span class="header-section-number">5.2.2</span> [2] Which places did this individual visit?<a href="data-manipulation-ii.html#which-places-did-this-individual-visit" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<ul>
<li><em>algorithmic solution</em>: we already found the oldest person, so now we only need his ID. We can use that id to filter the table which records relationships between individuals and places. After that we need to join those results with the table on places (to get their human-readable names) and with the table on relationships to places (to get more details on how exactly our oldest person is connected to those places). We can simply print out the resultant table in order to sum up the results.</li>
<li><em>complete solution</em>:</li>
</ul>
<div class="sourceCode" id="cb61"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb61-1"><a href="data-manipulation-ii.html#cb61-1" tabindex="-1"></a>oldestPersonID <span class="ot">&lt;-</span> oldest<span class="sc">$</span>idPersonaje</span>
<span id="cb61-2"><a href="data-manipulation-ii.html#cb61-2" tabindex="-1"></a></span>
<span id="cb61-3"><a href="data-manipulation-ii.html#cb61-3" tabindex="-1"></a>places <span class="ot">&lt;-</span> PUA<span class="sc">$</span>personaje_lugar <span class="sc">%&gt;%</span></span>
<span id="cb61-4"><a href="data-manipulation-ii.html#cb61-4" tabindex="-1"></a>  <span class="fu">filter</span>(idPersonaje <span class="sc">==</span> oldestPersonID) <span class="sc">%&gt;%</span></span>
<span id="cb61-5"><a href="data-manipulation-ii.html#cb61-5" tabindex="-1"></a>  <span class="fu">left_join</span>(PUA<span class="sc">$</span>lugar, <span class="at">by =</span> <span class="fu">c</span>(<span class="st">&quot;idLugar&quot;</span> <span class="ot">=</span> <span class="st">&quot;idLugar&quot;</span>)) <span class="sc">%&gt;%</span></span>
<span id="cb61-6"><a href="data-manipulation-ii.html#cb61-6" tabindex="-1"></a>  <span class="fu">left_join</span>(PUA<span class="sc">$</span>tiporelacionlugar, <span class="at">by =</span> <span class="fu">c</span>(<span class="st">&quot;idTipoRelacionLugar&quot;</span> <span class="ot">=</span> <span class="st">&quot;idTipoRelacionLugar&quot;</span>))</span>
<span id="cb61-7"><a href="data-manipulation-ii.html#cb61-7" tabindex="-1"></a></span>
<span id="cb61-8"><a href="data-manipulation-ii.html#cb61-8" tabindex="-1"></a>placesLite <span class="ot">&lt;-</span> places <span class="sc">%&gt;%</span></span>
<span id="cb61-9"><a href="data-manipulation-ii.html#cb61-9" tabindex="-1"></a>  <span class="fu">select</span>(nombre.x, nombre_castellano, nombre.y)</span>
<span id="cb61-10"><a href="data-manipulation-ii.html#cb61-10" tabindex="-1"></a></span>
<span id="cb61-11"><a href="data-manipulation-ii.html#cb61-11" tabindex="-1"></a>placesLite</span></code></pre></div>
<pre><code>## # A tibble: 6 × 3
##   nombre.x nombre_castellano nombre.y   
##   &lt;chr&gt;    &lt;chr&gt;             &lt;chr&gt;      
## 1 تدمير    Tudmīr            _RL_01AHL  
## 2 مرسية    Murcia            _RL_01AHL  
## 3 المشرق   Oriente           _RL_24RAHAL
## 4 مكة      La Meca           _RL_17HAGG 
## 5 القيروان Qayrawan          _RL_33KANA 
## 6 مصر      El Cairo          _RL_33KANA</code></pre>
<ul>
<li><em>human-readable solution:</em> just add the description based on the table; you can incorporate in-text code chunks like in the problem before, but it is not really necessary, since the data is more complex here.</li>
</ul>
<div class="sourceCode" id="cb63"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb63-1"><a href="data-manipulation-ii.html#cb63-1" tabindex="-1"></a>From the results we know that the oldest <span class="fu">individual</span> (let<span class="st">&#39;s call him al-Ṣabbāḥ,</span></span>
<span id="cb63-2"><a href="data-manipulation-ii.html#cb63-2" tabindex="-1"></a><span class="st">by his first name) has connections to the following places:</span></span>
<span id="cb63-3"><a href="data-manipulation-ii.html#cb63-3" tabindex="-1"></a><span class="st">`r paste0(placesLite$nombre_castellano)` (In Arabic their names would be,</span></span>
<span id="cb63-4"><a href="data-manipulation-ii.html#cb63-4" tabindex="-1"></a><span class="st">respectively: `r paste0(placesLite$nombre.x)`). From the types of relationships</span></span>
<span id="cb63-5"><a href="data-manipulation-ii.html#cb63-5" tabindex="-1"></a><span class="st">to places we can say that he was most closely connected to the cities of Tudmīr</span></span>
<span id="cb63-6"><a href="data-manipulation-ii.html#cb63-6" tabindex="-1"></a><span class="st">and Murcia (*min ahl ...*, “from the people of ...”). We know that he made a trip</span></span>
<span id="cb63-7"><a href="data-manipulation-ii.html#cb63-7" tabindex="-1"></a><span class="st">(*riḥlaŧ*) to the East of the Islamic world (*raḥala ilá al-Mašriq*). He “was”</span></span>
<span id="cb63-8"><a href="data-manipulation-ii.html#cb63-8" tabindex="-1"></a><span class="st">(*kāna*) in Qayrawan and Cairo (El Cairo); and that he performed “the greater</span></span>
<span id="cb63-9"><a href="data-manipulation-ii.html#cb63-9" tabindex="-1"></a><span class="st">pilgrimage” (*ḥajja*), meaning that he also visited Mecca (La Meca).</span></span></code></pre></div>
<blockquote>
<p><strong>The result will look like</strong>: From the results we know that the oldest individual (let’s call him al-Ṣabbāḥ, by his first name) has connections to the following places: Tudmīr, Murcia, Oriente, La Meca, Qayrawan, El Cairo (In Arabic their names would be, respectively: تدمير, مرسية, المشرق, مكة, القيروان, مصر). From the types of relationships to places we can say that he was most closely connected to the cities of Tudmīr and Murcia (<em>min ahl …</em>, “from the people of …”). We know that he made a trip (<em>riḥlaŧ</em>) to the East of the Islamic world (<em>raḥala ilá al-Mašriq</em>). He “was” (<em>kāna</em>) in Qayrawan and Cairo (El Cairo); and that he performed “the greater pilgrimage” (<em>ḥajja</em>), meaning that he also visited Mecca (La Meca).</p>
</blockquote>
</div>
<div id="what-kind-of-activities-was-that-individual-involved-in" class="section level3 hasAnchor" number="5.2.3">
<h3><span class="header-section-number">5.2.3</span> [3] What kind of activities was that individual involved in?<a href="data-manipulation-ii.html#what-kind-of-activities-was-that-individual-involved-in" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<ul>
<li><em>algorithmic solution</em>: we do have the ID of al-Ṣabbāḥ. Now, we essentially need to repeat the steps that we did in the previous problem, but we need to focus on the tables that record relationships between individuals and activities.</li>
<li><em>complete solution</em>:</li>
</ul>
<p><strong>Note:</strong> it makes sense to always check your intermediary results—this will allow you to check whether your steps are correct, and, perhaps, discover that your do not need to go all the way, like in the example below.</p>
<pre><code>oldestPersonID &lt;- oldest$idPersonaje

activities &lt;- PUA$personaje_actividad %&gt;%
  filter(idPersonaje == oldestPersonID)

activities</code></pre>
<p>Our intermediary results will look like the following:</p>
<pre><code># A tibble: 0 × 4
# ℹ 4 variables: idPersonaje &lt;dbl&gt;, idActividad &lt;dbl&gt;, fechaActividad &lt;dbl&gt;,
#   notas &lt;chr&gt;</code></pre>
<p>Essentially, we got an empty tibble. What does this mean? This means that we have no records on the activities of al-Ṣabbāḥ. And that is your solution/answer to the problem. Data in Arabic biographical dictionaries is often quite robust, but also quite often we have only very scarce details on specific individuals.</p>
<ul>
<li><em>human-readable solution:</em></li>
</ul>
<blockquote>
<p>We do not have any information on any activities of al-Ṣabbāḥ, the oldest individual in the PUA database.</p>
</blockquote>
</div>
<div id="who-is-the-oldest-jurist-faqīh-in-the-pua-data" class="section level3 hasAnchor" number="5.2.4">
<h3><span class="header-section-number">5.2.4</span> [4] Who is the oldest jurist (<em>faqīh</em>) in the PUA data?<a href="data-manipulation-ii.html#who-is-the-oldest-jurist-faqīh-in-the-pua-data" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<ul>
<li><em>algorithmic solution</em>: first of all, we need to find all the activities that can be classified as <em>jurist</em> in the table on activities. The only way to do that is actually to eyeball the table with activities: you need to open the table and find all the fitting activities. (To simplify things a little bit, we can focus only on activities that have “alfaquí” in the column <code>nombre_castellano</code>—there are 4 of those; if you do a serious research, however, you should carefully study the list of activities and check what else might fit the definition of a jurist.). Second, we need to filter the table that records relationships between activities and individuals, so that we only have individuals with activities in the area of jurisprudence. Third, we need to join our results with the main table on individuals—and then find the oldest of these individuals (like we did in the very first problem).</li>
<li><em>complete solution</em>:</li>
</ul>
<div class="sourceCode" id="cb66"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb66-1"><a href="data-manipulation-ii.html#cb66-1" tabindex="-1"></a><span class="co">#View(PUA$actividad) # use this to view the table, but do not include it into</span></span>
<span id="cb66-2"><a href="data-manipulation-ii.html#cb66-2" tabindex="-1"></a><span class="co">#the active chunk as it may interfere with the knitting of your notebook.</span></span>
<span id="cb66-3"><a href="data-manipulation-ii.html#cb66-3" tabindex="-1"></a></span>
<span id="cb66-4"><a href="data-manipulation-ii.html#cb66-4" tabindex="-1"></a>juristActivities <span class="ot">&lt;-</span> PUA<span class="sc">$</span>actividad <span class="sc">%&gt;%</span></span>
<span id="cb66-5"><a href="data-manipulation-ii.html#cb66-5" tabindex="-1"></a>  <span class="fu">filter</span>(<span class="fu">str_detect</span>(nombre_castellano, <span class="st">&quot;alfaquí&quot;</span>))</span>
<span id="cb66-6"><a href="data-manipulation-ii.html#cb66-6" tabindex="-1"></a></span>
<span id="cb66-7"><a href="data-manipulation-ii.html#cb66-7" tabindex="-1"></a>juristActivitiesIDs <span class="ot">&lt;-</span> juristActivities<span class="sc">$</span>idActividad</span>
<span id="cb66-8"><a href="data-manipulation-ii.html#cb66-8" tabindex="-1"></a><span class="co"># This step will give us the vector of IDs of relevant activities: 174, 59, 60, 67</span></span>
<span id="cb66-9"><a href="data-manipulation-ii.html#cb66-9" tabindex="-1"></a></span>
<span id="cb66-10"><a href="data-manipulation-ii.html#cb66-10" tabindex="-1"></a>oldestJurist <span class="ot">&lt;-</span> PUA<span class="sc">$</span>personaje_actividad <span class="sc">%&gt;%</span></span>
<span id="cb66-11"><a href="data-manipulation-ii.html#cb66-11" tabindex="-1"></a>  <span class="fu">filter</span>(idActividad <span class="sc">%in%</span> juristActivitiesIDs) <span class="sc">%&gt;%</span></span>
<span id="cb66-12"><a href="data-manipulation-ii.html#cb66-12" tabindex="-1"></a>  <span class="fu">left_join</span>(PUA<span class="sc">$</span>personaje, <span class="at">by =</span> <span class="fu">c</span>(<span class="st">&quot;idPersonaje&quot;</span> <span class="ot">=</span> <span class="st">&quot;idPersonaje&quot;</span>)) <span class="sc">%&gt;%</span></span>
<span id="cb66-13"><a href="data-manipulation-ii.html#cb66-13" tabindex="-1"></a>  <span class="fu">top_n</span>(<span class="dv">1</span>, edad)</span></code></pre></div>
<p><strong>Note:</strong> the operator <code>%in%</code> is used in R to test whether the elements of one vector are present in another vector. This is the best way to filter one vector by another.</p>
<p>The table below shows different types of jurists that we have in the activities table:</p>
<div class="sourceCode" id="cb67"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb67-1"><a href="data-manipulation-ii.html#cb67-1" tabindex="-1"></a>juristActivities</span></code></pre></div>
<pre><code>## # A tibble: 4 × 5
##   idActividad nombre     nombre_castellano notas descripcion
##         &lt;dbl&gt; &lt;chr&gt;      &lt;chr&gt;             &lt;chr&gt; &lt;chr&gt;      
## 1         174 فقيه ظاهري alfaquí zāhirí    &lt;NA&gt;  &lt;NA&gt;       
## 2          59 فقيه       alfaquí           &lt;NA&gt;  &lt;NA&gt;       
## 3          60 فقيه مالكي alfaquí mālikí    &lt;NA&gt;  &lt;NA&gt;       
## 4          67 فقيه شافعي alfaquí šāfiʿí    &lt;NA&gt;  &lt;NA&gt;</code></pre>
<ul>
<li><em>human-readable solution:</em> since our results are structurally very similar to those of the first problem, we can format our reply in a similar manner.</li>
</ul>
<div class="sourceCode" id="cb69"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb69-1"><a href="data-manipulation-ii.html#cb69-1" tabindex="-1"></a>The oldest jurist <span class="cf">in</span> the PUA database is<span class="sc">:</span> <span class="st">`</span><span class="at">r oldestJurist$nombreE</span><span class="st">`</span>.</span>
<span id="cb69-2"><a href="data-manipulation-ii.html#cb69-2" tabindex="-1"></a>His Arabic name is <span class="st">``</span>r oldestJurist<span class="sc">$</span>nombreA<span class="st">``</span>. He died at the age</span>
<span id="cb69-3"><a href="data-manipulation-ii.html#cb69-3" tabindex="-1"></a>of <span class="st">`</span><span class="at">r oldestJurist$edad</span><span class="st">`</span> <span class="cf">in</span> <span class="st">`</span><span class="at">r oldestJurist$muerte</span><span class="st">`</span> AH <span class="sc">/</span></span>
<span id="cb69-4"><a href="data-manipulation-ii.html#cb69-4" tabindex="-1"></a><span class="st">`</span><span class="at">r oldestJurist$muerteec</span><span class="st">`</span> CE.<span class="st">`</span></span></code></pre></div>
<blockquote>
<p><strong>The result will look like</strong>: The oldest jurist in the PUA database is: ʿAbd Allāh b. Ayyūb al-Anṣārī, Ibn Ḫayruǧ (/Ḫaḏūg / Ḫarūg), Abū Muḥammad,. His Arabic name is <code>عبد الله بن أيوب الأنصاري، ابن خيروج (/ ابن خذوج / ابن خروج)، أبو محمد</code>. He died at the age of 100 in 562 AH / 1166 CE.</p>
</blockquote>
<p>###[5] Can you find a person who traveled the most?</p>
<ul>
<li><em>algorithmic solution</em>: This problem is a bit tricky. We need to begin with a quick discussion of how exactly we represent “traveled the most”. The easiest way would be to think of an individual who has the highest number of places associated with his/her name. Thus, we need to count the number of places associated with each individual in the table that records relationships between individuals and places. Then, we need to find an individual who has the highest number of places. We, then, may want to join our results with the main table on individuals to get more details on our traveller.<br />
</li>
<li><em>complete solution</em>:</li>
</ul>
<div class="sourceCode" id="cb70"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb70-1"><a href="data-manipulation-ii.html#cb70-1" tabindex="-1"></a>traveller <span class="ot">&lt;-</span> PUA<span class="sc">$</span>personaje_lugar <span class="sc">%&gt;%</span></span>
<span id="cb70-2"><a href="data-manipulation-ii.html#cb70-2" tabindex="-1"></a>  <span class="fu">group_by</span>(idPersonaje) <span class="sc">%&gt;%</span></span>
<span id="cb70-3"><a href="data-manipulation-ii.html#cb70-3" tabindex="-1"></a>  <span class="fu">summarize</span>(<span class="at">placesTotal =</span> <span class="fu">n</span>()) <span class="sc">%&gt;%</span></span>
<span id="cb70-4"><a href="data-manipulation-ii.html#cb70-4" tabindex="-1"></a>  <span class="fu">top_n</span>(<span class="dv">1</span>, <span class="at">wt =</span> placesTotal) <span class="sc">%&gt;%</span></span>
<span id="cb70-5"><a href="data-manipulation-ii.html#cb70-5" tabindex="-1"></a>  <span class="fu">left_join</span>(PUA<span class="sc">$</span>personaje)</span></code></pre></div>
<pre><code>## Joining with `by = join_by(idPersonaje)`</code></pre>
<ul>
<li><em>human-readable solution:</em></li>
</ul>
<div class="sourceCode" id="cb72"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb72-1"><a href="data-manipulation-ii.html#cb72-1" tabindex="-1"></a>The person who travelled the most has visited <span class="st">`</span><span class="at">r traveller$placesTotal</span><span class="st">`</span></span>
<span id="cb72-2"><a href="data-manipulation-ii.html#cb72-2" tabindex="-1"></a>places. His name is<span class="sc">:</span> <span class="st">`</span><span class="at">r traveller$nombreE</span><span class="st">`</span>. His Arabic name is </span>
<span id="cb72-3"><a href="data-manipulation-ii.html#cb72-3" tabindex="-1"></a><span class="st">`</span><span class="at">r traveller$nombreA</span><span class="st">``</span><span class="at">. He died at the age of </span><span class="st">`</span>r traveller<span class="sc">$</span>edad<span class="st">`</span><span class="at"> in</span></span>
<span id="cb72-4"><a href="data-manipulation-ii.html#cb72-4" tabindex="-1"></a><span class="st">`</span>r traveller<span class="sc">$</span>muerte<span class="st">`</span><span class="at"> AH / </span><span class="st">`</span>r traveller<span class="sc">$</span>muerteec<span class="st">`</span><span class="at"> CE. There is a short</span></span>
<span id="cb72-5"><a href="data-manipulation-ii.html#cb72-5" tabindex="-1"></a><span class="at">biographical note on him in Spanish: *</span><span class="st">`</span>r traveller<span class="sc">$</span>resumenBiografico<span class="st">`</span><span class="at">*.</span></span></code></pre></div>
<blockquote>
<p><strong>The result will look like</strong>: The person who travelled the most has visited 32 places. His name is: ʿAlī b. Mūsà b. Muḥammad b. ʿAbd al-Malik b. Saʿīd b. Ḫalaf b. Saʿīd b. Muḥammad b. ʿAbd Allāh b. Saʿīd b. al-Ḥasan b. ʿUṯmān b. ʿAbd Allāh b. Saʿd b. ʿAmmār b. Yāsir b. Kināna b. Qays b. al-Ḥaṣīn b. Lawḏan b. Ṯaʿlaba b. ʿAwf b. Ḥāriṯa b. ʿĀmir al-Akbar b. Nām b. ʿAbs al-ʿAnsī al-Maḏḥiğī, Ibn Saʿīd, Abū l-Ḥasan. His Arabic name is <code>علي بن موسى بن محمد بن عبد الملك بن سعيد بن خلف بن سعيد بن محمد بن عبد الله بن سعيد بن الحسن بن عثمان بن عبد الله بن سعد بن عمار بن ياسر بن كنانة بن قيس بن الحصين بن لوذم بن ثعلب بن عوف بن حارثة بن عامر الأكبر بن نام بن عبس العنسي المذحجي، ابن سعيد، أبو الحسن</code>. He died at the age of 75 in 685 AH / 1286 CE. There is a short biographical note on him in Spanish: <em>Célebre historiador, geógrafo y poeta nacido en 610/1213 en Alcalá la Real. Tras haber viajado por diversas ciudades de Oriente, haciendo varias veces la peregrinación a la Meca, falleció en Túnez en 685/1286. Fue autor, entre otras obras no conservadas, de Al-Mugrib fī ḥulà l-Magrib, Rāyāt al-mubarrizīn wa-gāyāt al-mumayyizīn, Iḫtiṣār al-Qidḥ al-muʿallà fī l-taʾrīḫ al-muḥallà, utilizadas aquí como fuente</em>.</p>
</blockquote>
<blockquote>
<blockquote>
<p>(<strong>English</strong>: Celebrated historian, geographer, and poet born in 610/1213 in Alcalá la Real. After having traveled through various cities in the East, making several pilgrimages to Mecca, he died in Tunisia in 685/1286. He was the author, among other works that have not been preserved, of Al-Mugrib fī ḥulà l-Magrib, Rāyāt al-mubarrizīn wa-gāyāt al-mumayyizīn, Iḫtiṣār al-Qidḥ al-muʿallà fī l-taʾrīḫ al-muḥallà, used here as a source.)</p>
</blockquote>
</blockquote>
<p><strong>Note:</strong> a better solution (following Covadonga)</p>
<div class="sourceCode" id="cb73"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb73-1"><a href="data-manipulation-ii.html#cb73-1" tabindex="-1"></a>travellerPlaces <span class="ot">&lt;-</span> traveller <span class="sc">%&gt;%</span></span>
<span id="cb73-2"><a href="data-manipulation-ii.html#cb73-2" tabindex="-1"></a>  <span class="fu">left_join</span>(PUA<span class="sc">$</span>personaje_lugar) <span class="sc">%&gt;%</span></span>
<span id="cb73-3"><a href="data-manipulation-ii.html#cb73-3" tabindex="-1"></a>  <span class="fu">left_join</span>(PUA<span class="sc">$</span>lugar)</span></code></pre></div>
<pre><code>## Joining with `by = join_by(idPersonaje)`
## Joining with `by = join_by(idLugar)`</code></pre>
<blockquote>
<p><strong>Additional details:</strong></p>
</blockquote>
<div class="sourceCode" id="cb75"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb75-1"><a href="data-manipulation-ii.html#cb75-1" tabindex="-1"></a>Our traveller <span class="st">`</span><span class="at">r length(unique(travellerPlaces$nombre_castellano))</span><span class="st">`</span> places,</span>
<span id="cb75-2"><a href="data-manipulation-ii.html#cb75-2" tabindex="-1"></a>which are<span class="sc">:</span> <span class="st">`</span><span class="at">r unique(travellerPlaces$nombre_castellano)</span><span class="st">`</span>.</span></code></pre></div>
<blockquote>
<p><strong>Rendered as:</strong> Our traveller visited 30 places, which are: Ifrīqiya, Alcalá la Real, al-ʿIdwa, Alejandría, El Cairo, Alepo, Mosul, Bagdad, Túnez, Granada, Sevilla, Damasco, Oriente, Egipto, Jerusalén, Émesa, Basora, La Meca, Arrağān, Kelibia, Carmona, Sanğār, Tal Afar, Arcos, Algeciras, Jerez, Medina Sidonia, Málaga, Ceuta, Hama.</p>
</blockquote>
</div>
<div id="can-you-find-a-century-in-which-andalusians-traveled-the-most" class="section level3 hasAnchor" number="5.2.5">
<h3><span class="header-section-number">5.2.5</span> [6] Can you find a century in which Andalusians traveled the most?<a href="data-manipulation-ii.html#can-you-find-a-century-in-which-andalusians-traveled-the-most" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<ul>
<li><p><em>algorithmic solution</em>: we need to aggregate data on individuals into centuries—for now, let’s simply round up death dates to the next 100; in actual research you would prefer doing something more elaborate, but this simplified approach will suffice for now. In any case, however, you always need to explain how you “implement” your data: in our case, we simply round up death dates to the next 100. Second, we will count the number of places associated with each individual. After connecting two tables (which should in the end have columns: person, century, number of visited places), we should calculate some number that would indicate the number of travels. The easiest would be to calculate average mean (<code>mean()</code>), but the problem with the mean is that it is too sensitive to outliers.</p></li>
<li><p>In the example below, for <code>vector</code> the mean is 8.467, while the majority of numbers are 2s. We can get a better picture by looking at interquartile range, which is the range between the 1st quarter and the 3rd quarter—values that we can get with <code>summary()</code>. In both cases we get 2s, which means that the middle 50% of all values are 2s. Since we have the range, we will need to look at the results (but we can still try to arrange by the value of the 1st quartile).</p></li>
</ul>
<div class="sourceCode" id="cb76"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb76-1"><a href="data-manipulation-ii.html#cb76-1" tabindex="-1"></a>vector <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">1</span>,<span class="dv">2</span>,<span class="dv">2</span>,<span class="dv">2</span>,<span class="dv">2</span>,<span class="dv">2</span>,<span class="dv">2</span>,<span class="dv">2</span>,<span class="dv">2</span>,<span class="dv">2</span>,<span class="dv">2</span>,<span class="dv">2</span>,<span class="dv">2</span>,<span class="dv">2</span>,<span class="dv">100</span>)</span>
<span id="cb76-2"><a href="data-manipulation-ii.html#cb76-2" tabindex="-1"></a></span>
<span id="cb76-3"><a href="data-manipulation-ii.html#cb76-3" tabindex="-1"></a><span class="fu">mean</span>(vector)</span>
<span id="cb76-4"><a href="data-manipulation-ii.html#cb76-4" tabindex="-1"></a><span class="co"># [1] 8.466667</span></span>
<span id="cb76-5"><a href="data-manipulation-ii.html#cb76-5" tabindex="-1"></a></span>
<span id="cb76-6"><a href="data-manipulation-ii.html#cb76-6" tabindex="-1"></a><span class="fu">summary</span>(vector)</span>
<span id="cb76-7"><a href="data-manipulation-ii.html#cb76-7" tabindex="-1"></a><span class="co">#[1] 8.466667</span></span>
<span id="cb76-8"><a href="data-manipulation-ii.html#cb76-8" tabindex="-1"></a><span class="co">#   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. </span></span>
<span id="cb76-9"><a href="data-manipulation-ii.html#cb76-9" tabindex="-1"></a><span class="co">#  1.000   2.000   2.000   8.467   2.000 100.000</span></span>
<span id="cb76-10"><a href="data-manipulation-ii.html#cb76-10" tabindex="-1"></a></span>
<span id="cb76-11"><a href="data-manipulation-ii.html#cb76-11" tabindex="-1"></a>q1 <span class="ot">&lt;-</span> <span class="fu">summary</span>(vector)[[<span class="dv">2</span>]]</span>
<span id="cb76-12"><a href="data-manipulation-ii.html#cb76-12" tabindex="-1"></a>q3 <span class="ot">&lt;-</span> <span class="fu">summary</span>(vector)[[<span class="dv">5</span>]]</span></code></pre></div>
<ul>
<li><em>complete solution</em>:</li>
</ul>
<div class="sourceCode" id="cb77"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb77-1"><a href="data-manipulation-ii.html#cb77-1" tabindex="-1"></a>visitedPlaces <span class="ot">&lt;-</span> PUA<span class="sc">$</span>personaje_lugar <span class="sc">%&gt;%</span></span>
<span id="cb77-2"><a href="data-manipulation-ii.html#cb77-2" tabindex="-1"></a>  <span class="fu">select</span>(idPersonaje, idLugar) <span class="sc">%&gt;%</span></span>
<span id="cb77-3"><a href="data-manipulation-ii.html#cb77-3" tabindex="-1"></a>  <span class="fu">unique</span>()</span>
<span id="cb77-4"><a href="data-manipulation-ii.html#cb77-4" tabindex="-1"></a></span>
<span id="cb77-5"><a href="data-manipulation-ii.html#cb77-5" tabindex="-1"></a>travellersByCenturies <span class="ot">&lt;-</span> PUA<span class="sc">$</span>personaje <span class="sc">%&gt;%</span></span>
<span id="cb77-6"><a href="data-manipulation-ii.html#cb77-6" tabindex="-1"></a>  <span class="fu">left_join</span>(visitedPlaces) <span class="sc">%&gt;%</span></span>
<span id="cb77-7"><a href="data-manipulation-ii.html#cb77-7" tabindex="-1"></a>  <span class="fu">group_by</span>(idPersonaje, muerte) <span class="sc">%&gt;%</span></span>
<span id="cb77-8"><a href="data-manipulation-ii.html#cb77-8" tabindex="-1"></a>  <span class="fu">summarize</span>(<span class="at">totalPlaces =</span> <span class="fu">n</span>()) <span class="sc">%&gt;%</span></span>
<span id="cb77-9"><a href="data-manipulation-ii.html#cb77-9" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">century =</span> <span class="fu">ceiling</span>(muerte <span class="sc">/</span> <span class="dv">100</span>) <span class="sc">*</span> <span class="dv">100</span>) <span class="sc">%&gt;%</span></span>
<span id="cb77-10"><a href="data-manipulation-ii.html#cb77-10" tabindex="-1"></a>  <span class="fu">group_by</span>(century) <span class="sc">%&gt;%</span></span>
<span id="cb77-11"><a href="data-manipulation-ii.html#cb77-11" tabindex="-1"></a>  <span class="fu">summarize</span>(<span class="at">q1 =</span> <span class="fu">summary</span>(totalPlaces)[[<span class="dv">2</span>]],</span>
<span id="cb77-12"><a href="data-manipulation-ii.html#cb77-12" tabindex="-1"></a>            <span class="at">q3 =</span> <span class="fu">summary</span>(totalPlaces)[[<span class="dv">5</span>]],</span>
<span id="cb77-13"><a href="data-manipulation-ii.html#cb77-13" tabindex="-1"></a>            <span class="at">mean =</span> <span class="fu">mean</span>(totalPlaces),</span>
<span id="cb77-14"><a href="data-manipulation-ii.html#cb77-14" tabindex="-1"></a>            <span class="at">total =</span> <span class="fu">n</span>()) <span class="sc">%&gt;%</span></span>
<span id="cb77-15"><a href="data-manipulation-ii.html#cb77-15" tabindex="-1"></a>  <span class="fu">arrange</span>(century)</span></code></pre></div>
<pre><code>## Joining with `by = join_by(idPersonaje)`
## `summarise()` has grouped output by &#39;idPersonaje&#39;. You can override using the `.groups` argument.</code></pre>
<p>The results will look like:</p>
<div class="sourceCode" id="cb79"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb79-1"><a href="data-manipulation-ii.html#cb79-1" tabindex="-1"></a>travellersByCenturies</span></code></pre></div>
<pre><code>## # A tibble: 12 × 5
##    century    q1    q3  mean total
##      &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;int&gt;
##  1       0   1     1    1.26  5715
##  2     100   1     3    3       13
##  3     200   1     3    2.27    83
##  4     300   1     4    2.86   407
##  5     400   1     3    2.75  1275
##  6     500   1     3    2.15  1482
##  7     600   1     3    2.35  1983
##  8     700   1     4    2.97  1246
##  9     800   1     3    2.16   452
## 10     900   1     1    1.79    39
## 11    1000   1.5   2.5  2        3
## 12      NA   1     1    1      115</code></pre>
<ul>
<li><em>human-readable solution:</em> On average, 50% of individuals in each century travelled to 1-3 places, with 3rd and 7th centuries having a slightly higher volume of travel between 1 and 4 places for the interquartile range. One may argue that the average level of traveling remained quite similar through the centuries (the average mean does not change significantly either). Alternatively, perhaps, we need a different way to calculate that.</li>
</ul>
</div>
<div id="what-are-the-10-most-common-activities-andalusians-were-involved-into" class="section level3 hasAnchor" number="5.2.6">
<h3><span class="header-section-number">5.2.6</span> [7] What are the 10 most common activities Andalusians were involved into?<a href="data-manipulation-ii.html#what-are-the-10-most-common-activities-andalusians-were-involved-into" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<ul>
<li><em>algorithmic solution</em>: We need to count instances of all activities (table that connects individuals and activities). Then we simply find the top ten.</li>
<li><em>complete solution</em>:</li>
</ul>
<div class="sourceCode" id="cb81"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb81-1"><a href="data-manipulation-ii.html#cb81-1" tabindex="-1"></a>activities <span class="ot">&lt;-</span> PUA<span class="sc">$</span>personaje_actividad <span class="sc">%&gt;%</span></span>
<span id="cb81-2"><a href="data-manipulation-ii.html#cb81-2" tabindex="-1"></a>  <span class="fu">group_by</span>(idActividad) <span class="sc">%&gt;%</span></span>
<span id="cb81-3"><a href="data-manipulation-ii.html#cb81-3" tabindex="-1"></a>  <span class="fu">summarize</span>(<span class="at">total =</span> <span class="fu">n</span>()) <span class="sc">%&gt;%</span></span>
<span id="cb81-4"><a href="data-manipulation-ii.html#cb81-4" tabindex="-1"></a>  <span class="fu">left_join</span>(PUA<span class="sc">$</span>actividad) <span class="sc">%&gt;%</span></span>
<span id="cb81-5"><a href="data-manipulation-ii.html#cb81-5" tabindex="-1"></a>  <span class="fu">top_n</span>(<span class="dv">10</span>, <span class="at">wt =</span> total) <span class="sc">%&gt;%</span></span>
<span id="cb81-6"><a href="data-manipulation-ii.html#cb81-6" tabindex="-1"></a>  <span class="fu">arrange</span>(<span class="fu">desc</span>(total)) <span class="sc">%&gt;%</span></span>
<span id="cb81-7"><a href="data-manipulation-ii.html#cb81-7" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">readable =</span> <span class="fu">paste0</span>(nombre_castellano, <span class="st">&quot; (&quot;</span>, nombre, <span class="st">&quot;) --- &quot;</span>, total, <span class="st">&quot; individuals&quot;</span>)) <span class="sc">%&gt;%</span></span>
<span id="cb81-8"><a href="data-manipulation-ii.html#cb81-8" tabindex="-1"></a>  <span class="fu">select</span>(readable)</span></code></pre></div>
<pre><code>## Joining with `by = join_by(idActividad)`</code></pre>
<div class="sourceCode" id="cb83"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb83-1"><a href="data-manipulation-ii.html#cb83-1" tabindex="-1"></a>activities</span></code></pre></div>
<pre><code>## # A tibble: 10 × 1
##    readable                                              
##    &lt;chr&gt;                                                 
##  1 alfaquí (فقيه) --- 725 individuals                    
##  2 letrado (أديب) --- 464 individuals                    
##  3 almocrí (مقرىء) --- 417 individuals                   
##  4 poeta (شاعر) --- 406 individuals                      
##  5 tradicionista (محدث) --- 331 individuals              
##  6 gramático (نحوي) --- 156 individuals                  
##  7 secretario, escribano (كاتب) --- 103 individuals      
##  8 redactor de contratos (عاقد للشروط) --- 78 individuals
##  9 médico (طبيب) --- 52 individuals                      
## 10 lexicógrafo (لغوي) --- 52 individuals</code></pre>
<ul>
<li><em>human-readable solution:</em></li>
</ul>
<div class="sourceCode" id="cb85"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb85-1"><a href="data-manipulation-ii.html#cb85-1" tabindex="-1"></a>The most common activities among Andalusians are<span class="sc">:</span></span>
<span id="cb85-2"><a href="data-manipulation-ii.html#cb85-2" tabindex="-1"></a><span class="st">`</span><span class="at">r paste0(activities$readable, collapse = &quot;; &quot;)</span><span class="st">`</span>.</span></code></pre></div>
<blockquote>
<p><strong>Rendered as:</strong> The most common activities among Andalusians are: alfaquí (فقيه) — 725 individuals; letrado (أديب) — 464 individuals; almocrí (مقرىء) — 417 individuals; poeta (شاعر) — 406 individuals; tradicionista (محدث) — 331 individuals; gramático (نحوي) — 156 individuals; secretario, escribano (كاتب) — 103 individuals; redactor de contratos (عاقد للشروط) — 78 individuals; médico (طبيب) — 52 individuals; lexicógrafo (لغوي) — 52 individuals.</p>
</blockquote>
</div>
<div id="what-are-the-most-common-activities-in-the-5th-ah-century" class="section level3 hasAnchor" number="5.2.7">
<h3><span class="header-section-number">5.2.7</span> [8] What are the most common activities in the 5th AH century?<a href="data-manipulation-ii.html#what-are-the-most-common-activities-in-the-5th-ah-century" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<ul>
<li><p><em>algorithmic solution</em>: This is very similar to the previous one. What we need to change is, first, to identify all individual from the 5th century AH and then use this data to filter the table that connects individuals and activities. After that we process the results in the exact same way as in the previous problem.</p></li>
<li><p><em>complete solution</em>:</p></li>
</ul>
<div class="sourceCode" id="cb86"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb86-1"><a href="data-manipulation-ii.html#cb86-1" tabindex="-1"></a>people500AH <span class="ot">&lt;-</span> PUA<span class="sc">$</span>personaje <span class="sc">%&gt;%</span></span>
<span id="cb86-2"><a href="data-manipulation-ii.html#cb86-2" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">century =</span> <span class="fu">ceiling</span>(muerte <span class="sc">/</span> <span class="dv">100</span>) <span class="sc">*</span> <span class="dv">100</span>) <span class="sc">%&gt;%</span></span>
<span id="cb86-3"><a href="data-manipulation-ii.html#cb86-3" tabindex="-1"></a>  <span class="fu">filter</span>(century <span class="sc">==</span> <span class="dv">500</span>) <span class="sc">%&gt;%</span></span>
<span id="cb86-4"><a href="data-manipulation-ii.html#cb86-4" tabindex="-1"></a>  <span class="fu">left_join</span>(PUA<span class="sc">$</span>personaje_actividad) <span class="sc">%&gt;%</span></span>
<span id="cb86-5"><a href="data-manipulation-ii.html#cb86-5" tabindex="-1"></a>  <span class="fu">select</span>(idActividad) <span class="sc">%&gt;%</span></span>
<span id="cb86-6"><a href="data-manipulation-ii.html#cb86-6" tabindex="-1"></a>  <span class="fu">left_join</span>(PUA<span class="sc">$</span>actividad) <span class="sc">%&gt;%</span></span>
<span id="cb86-7"><a href="data-manipulation-ii.html#cb86-7" tabindex="-1"></a>  <span class="fu">group_by</span>(nombre_castellano, nombre) <span class="sc">%&gt;%</span></span>
<span id="cb86-8"><a href="data-manipulation-ii.html#cb86-8" tabindex="-1"></a>  <span class="fu">summarize</span>(<span class="at">total =</span> <span class="fu">n</span>()) <span class="sc">%&gt;%</span></span>
<span id="cb86-9"><a href="data-manipulation-ii.html#cb86-9" tabindex="-1"></a>  <span class="fu">arrange</span>(<span class="fu">desc</span>(total)) <span class="sc">%&gt;%</span></span>
<span id="cb86-10"><a href="data-manipulation-ii.html#cb86-10" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">readable =</span> <span class="fu">paste0</span>(nombre_castellano, <span class="st">&quot; (&quot;</span>, nombre, <span class="st">&quot;) --- &quot;</span>, total, <span class="st">&quot; individuals&quot;</span>)) <span class="sc">%&gt;%</span></span>
<span id="cb86-11"><a href="data-manipulation-ii.html#cb86-11" tabindex="-1"></a>  <span class="fu">ungroup</span>() <span class="sc">%&gt;%</span></span>
<span id="cb86-12"><a href="data-manipulation-ii.html#cb86-12" tabindex="-1"></a>  <span class="fu">top_n</span>(<span class="dv">10</span>, <span class="at">wt =</span> total) <span class="sc">%&gt;%</span></span>
<span id="cb86-13"><a href="data-manipulation-ii.html#cb86-13" tabindex="-1"></a>  <span class="fu">select</span>(readable)</span></code></pre></div>
<pre><code>## Joining with `by = join_by(idPersonaje)`
## Joining with `by = join_by(idActividad)`
## `summarise()` has grouped output by &#39;nombre_castellano&#39;. You can override using the `.groups` argument.</code></pre>
<div class="sourceCode" id="cb88"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb88-1"><a href="data-manipulation-ii.html#cb88-1" tabindex="-1"></a>people500AH</span></code></pre></div>
<pre><code>## # A tibble: 10 × 1
##    readable                               
##    &lt;chr&gt;                                  
##  1 NA (NA) --- 1216 individuals           
##  2 alfaquí (فقيه) --- 78 individuals      
##  3 almocrí (مقرىء) --- 63 individuals     
##  4 poeta (شاعر) --- 60 individuals        
##  5 letrado (أديب) --- 54 individuals      
##  6 tradicionista (محدث) --- 27 individuals
##  7 comerciante (تاجر) --- 26 individuals  
##  8 consejero (مشاور) --- 9 individuals    
##  9 lexicógrafo (لغوي) --- 8 individuals   
## 10 gramático (نحوي) --- 7 individuals</code></pre>
<ul>
<li><em>human-readable solution:</em></li>
</ul>
<div class="sourceCode" id="cb90"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb90-1"><a href="data-manipulation-ii.html#cb90-1" tabindex="-1"></a>The most common activities among Andalusians <span class="cf">in</span> the 5th century</span>
<span id="cb90-2"><a href="data-manipulation-ii.html#cb90-2" tabindex="-1"></a>AH are<span class="sc">:</span> <span class="st">`</span><span class="at">r paste0(people500AH$readable, collapse = &quot;; &quot;)</span><span class="st">`</span>. The first result essentially</span>
<span id="cb90-3"><a href="data-manipulation-ii.html#cb90-3" tabindex="-1"></a>means that <span class="cf">for</span> most Andalusians <span class="cf">in</span> the 5th century we actually</span>
<span id="cb90-4"><a href="data-manipulation-ii.html#cb90-4" tabindex="-1"></a>do not have any information on their activities.</span></code></pre></div>
<blockquote>
<p><strong>Rendered as:</strong> The most common activities among Andalusians in the 5th century AH are: NA (NA) — 1216 individuals; alfaquí (فقيه) — 78 individuals; almocrí (مقرىء) — 63 individuals; poeta (شاعر) — 60 individuals; letrado (أديب) — 54 individuals; tradicionista (محدث) — 27 individuals; comerciante (تاجر) — 26 individuals; consejero (مشاور) — 9 individuals; lexicógrafo (لغوي) — 8 individuals; gramático (نحوي) — 7 individuals. The first result essentially means that for most Andalusians in the 5th century we actually do not have any information on their activities.</p>
</blockquote>
</div>
<div id="what-are-the-main-locations-of-the-5-largest-families-places-from-familia" class="section level3 hasAnchor" number="5.2.8">
<h3><span class="header-section-number">5.2.8</span> [9] What are the main locations of the 5 largest families? (places from <code>familia</code>)<a href="data-manipulation-ii.html#what-are-the-main-locations-of-the-5-largest-families-places-from-familia" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<ul>
<li><p><em>algorithmic solution</em>: main locations are those that are mentioned in the table <code>familia</code>. We need to find those locations in the table <code>personaje_lugar</code> (filter by relationship type). We then need to find the top 5 families. Then we filter the table with persons by these top 5 families. We then connect resulting persons with filtered places and count people by places per family. The final results would be to create a “summary” column with readable information. Let’s see if this works :)</p></li>
<li><p><em>complete solution</em>:</p></li>
</ul>
<div class="sourceCode" id="cb91"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb91-1"><a href="data-manipulation-ii.html#cb91-1" tabindex="-1"></a>top5families <span class="ot">&lt;-</span> PUA<span class="sc">$</span>personaje <span class="sc">%&gt;%</span></span>
<span id="cb91-2"><a href="data-manipulation-ii.html#cb91-2" tabindex="-1"></a>  <span class="fu">filter</span>(idFamilia <span class="sc">!=</span> <span class="dv">0</span>) <span class="sc">%&gt;%</span></span>
<span id="cb91-3"><a href="data-manipulation-ii.html#cb91-3" tabindex="-1"></a>  <span class="fu">filter</span>(<span class="sc">!</span><span class="fu">is.na</span>(idFamilia)) <span class="sc">%&gt;%</span></span>
<span id="cb91-4"><a href="data-manipulation-ii.html#cb91-4" tabindex="-1"></a>  <span class="fu">group_by</span>(idFamilia) <span class="sc">%&gt;%</span></span>
<span id="cb91-5"><a href="data-manipulation-ii.html#cb91-5" tabindex="-1"></a>  <span class="fu">summarize</span>(<span class="at">totalMembers =</span> <span class="fu">n</span>()) <span class="sc">%&gt;%</span></span>
<span id="cb91-6"><a href="data-manipulation-ii.html#cb91-6" tabindex="-1"></a>  <span class="fu">top_n</span>(<span class="dv">20</span>, totalMembers) <span class="sc">%&gt;%</span></span>
<span id="cb91-7"><a href="data-manipulation-ii.html#cb91-7" tabindex="-1"></a>  <span class="fu">arrange</span>(<span class="fu">desc</span>(totalMembers)) <span class="sc">%&gt;%</span></span>
<span id="cb91-8"><a href="data-manipulation-ii.html#cb91-8" tabindex="-1"></a>  <span class="fu">left_join</span>(PUA<span class="sc">$</span>familia) <span class="sc">%&gt;%</span> </span>
<span id="cb91-9"><a href="data-manipulation-ii.html#cb91-9" tabindex="-1"></a>  <span class="fu">select</span>(totalMembers, nombreE, lugar, lugarOrigen, lugarTraslado) <span class="sc">%&gt;%</span></span>
<span id="cb91-10"><a href="data-manipulation-ii.html#cb91-10" tabindex="-1"></a>  <span class="fu">left_join</span>(PUA<span class="sc">$</span>lugar, <span class="at">by =</span> <span class="fu">c</span>(<span class="st">&quot;lugar&quot;</span> <span class="ot">=</span> <span class="st">&quot;idLugar&quot;</span>)) <span class="sc">%&gt;%</span></span>
<span id="cb91-11"><a href="data-manipulation-ii.html#cb91-11" tabindex="-1"></a>  <span class="fu">select</span>(totalMembers, nombreE, nombre_castellano, lugarOrigen, lugarTraslado) <span class="sc">%&gt;%</span></span>
<span id="cb91-12"><a href="data-manipulation-ii.html#cb91-12" tabindex="-1"></a>  <span class="fu">rename</span>(<span class="at">lugar =</span> nombre_castellano) <span class="sc">%&gt;%</span></span>
<span id="cb91-13"><a href="data-manipulation-ii.html#cb91-13" tabindex="-1"></a>  <span class="fu">left_join</span>(PUA<span class="sc">$</span>lugar, <span class="at">by =</span> <span class="fu">c</span>(<span class="st">&quot;lugarOrigen&quot;</span> <span class="ot">=</span> <span class="st">&quot;idLugar&quot;</span>)) <span class="sc">%&gt;%</span></span>
<span id="cb91-14"><a href="data-manipulation-ii.html#cb91-14" tabindex="-1"></a>  <span class="fu">select</span>(totalMembers, nombreE, lugar, nombre_castellano, lugarTraslado) <span class="sc">%&gt;%</span></span>
<span id="cb91-15"><a href="data-manipulation-ii.html#cb91-15" tabindex="-1"></a>  <span class="fu">rename</span>(<span class="at">lugarOrigen =</span> nombre_castellano) <span class="sc">%&gt;%</span></span>
<span id="cb91-16"><a href="data-manipulation-ii.html#cb91-16" tabindex="-1"></a>  <span class="fu">select</span>(totalMembers, nombreE, lugar, lugarOrigen, lugarTraslado) <span class="sc">%&gt;%</span></span>
<span id="cb91-17"><a href="data-manipulation-ii.html#cb91-17" tabindex="-1"></a>  <span class="fu">left_join</span>(PUA<span class="sc">$</span>lugar, <span class="at">by =</span> <span class="fu">c</span>(<span class="st">&quot;lugarTraslado&quot;</span> <span class="ot">=</span> <span class="st">&quot;idLugar&quot;</span>)) <span class="sc">%&gt;%</span></span>
<span id="cb91-18"><a href="data-manipulation-ii.html#cb91-18" tabindex="-1"></a>  <span class="fu">select</span>(totalMembers, nombreE, lugar, lugarOrigen, nombre_castellano) <span class="sc">%&gt;%</span></span>
<span id="cb91-19"><a href="data-manipulation-ii.html#cb91-19" tabindex="-1"></a>  <span class="fu">rename</span>(<span class="at">lugarTraslado =</span> nombre_castellano) <span class="sc">%&gt;%</span></span>
<span id="cb91-20"><a href="data-manipulation-ii.html#cb91-20" tabindex="-1"></a>  <span class="fu">select</span>(totalMembers, nombreE, lugar, lugarOrigen, lugarTraslado)</span></code></pre></div>
<pre><code>## Joining with `by = join_by(idFamilia)`</code></pre>
<div class="sourceCode" id="cb93"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb93-1"><a href="data-manipulation-ii.html#cb93-1" tabindex="-1"></a>top5families</span></code></pre></div>
<pre><code>## # A tibble: 21 × 5
##    totalMembers nombreE              lugar          lugarOrigen       lugarTraslado
##           &lt;int&gt; &lt;chr&gt;                &lt;chr&gt;          &lt;chr&gt;             &lt;chr&gt;        
##  1           23 Banū l-Bağī 1        &lt;NA&gt;           &lt;NA&gt;              &lt;NA&gt;         
##  2           23 Banū Saʿīd al-ʿAnsī  Alcalá la Real &lt;NA&gt;              Granada      
##  3           20 Banū Ḥağğağ al-Laḫmī Sevilla        &lt;NA&gt;              &lt;NA&gt;         
##  4           18 Banū Abī Ğamra       Murcia         &lt;NA&gt;              &lt;NA&gt;         
##  5           18 Banū ʿAmīra          Tudmīr         &lt;NA&gt;              &lt;NA&gt;         
##  6           16 Banū Ḫalīl al-Sakūnī Niebla         &lt;NA&gt;              &lt;NA&gt;         
##  7           16 Banū Hāniʾ           Granada        &lt;NA&gt;              &lt;NA&gt;         
##  8           15 Banū Dīnār           Córdoba        Toledo            &lt;NA&gt;         
##  9           15 Banū Qāsim b. Hilāl  Córdoba        &lt;NA&gt;              &lt;NA&gt;         
## 10           15 Banū Wāğib           Valencia       Beja (al-Andalus) &lt;NA&gt;         
## # ℹ 11 more rows</code></pre>
<ul>
<li><em>human-readable solution:</em> …</li>
</ul>
</div>
<div id="what-are-the-most-visited-locations-among-the-members-of-those-families-places-from-personaje_lugar" class="section level3 hasAnchor" number="5.2.9">
<h3><span class="header-section-number">5.2.9</span> [10] What are the most visited locations among the members of those families? (places from <code>personaje_lugar</code>)<a href="data-manipulation-ii.html#what-are-the-most-visited-locations-among-the-members-of-those-families-places-from-personaje_lugar" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<ul>
<li><em>algorithmic solution</em>: we can think of “main locations” as locations that are described with verb of residence and origin (AHL / ASL / SAKAN). We need to find those locations in the table personaje_lugar (filter by relationship type). We then need to find the top 5 families. Then we filter the table with persons by these top 5 families. We then connect resulting persons with filtered places and count people by places per family. The final results would be to create a “summary” column with readable information. Let’s see if this works :)</li>
<li><em>complete solution</em>: …</li>
<li><em>human-readable solution:</em> …</li>
</ul>
</div>
<div id="in-which-century-do-we-have-the-largest-number-of-families" class="section level3 hasAnchor" number="5.2.10">
<h3><span class="header-section-number">5.2.10</span> [11] In which century do we have the largest number of families?<a href="data-manipulation-ii.html#in-which-century-do-we-have-the-largest-number-of-families" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<ul>
<li><em>algorithmic solution</em>: …</li>
<li><em>complete solution</em>: …</li>
<li><em>human-readable solution:</em> …</li>
</ul>
</div>
<div id="what-is-the-peak-century-in-the-history-of-al-andalus-this-can-be-measured-by-the-highest-number-of-people." class="section level3 hasAnchor" number="5.2.11">
<h3><span class="header-section-number">5.2.11</span> [12] What is the peak century in the history of al-Andalus? (This can be measured by the highest number of people.)<a href="data-manipulation-ii.html#what-is-the-peak-century-in-the-history-of-al-andalus-this-can-be-measured-by-the-highest-number-of-people." class="anchor-section" aria-label="Anchor link to header"></a></h3>
<ul>
<li><em>algorithmic solution</em>: …</li>
<li><em>complete solution</em>: …</li>
<li><em>human-readable solution:</em> …</li>
</ul>
</div>
<div id="what-is-the-most-prominent-location-in-al-andalus-in-general-what-about-by-centuries-prominent-means-that-it-has-the-highest-number-of-people-associated-with-it." class="section level3 hasAnchor" number="5.2.12">
<h3><span class="header-section-number">5.2.12</span> [13] What is the most prominent location in al-Andalus in general? What about by centuries? (Prominent means that it has the highest number of people associated with it.)<a href="data-manipulation-ii.html#what-is-the-most-prominent-location-in-al-andalus-in-general-what-about-by-centuries-prominent-means-that-it-has-the-highest-number-of-people-associated-with-it." class="anchor-section" aria-label="Anchor link to header"></a></h3>
<ul>
<li><em>algorithmic solution</em>: …</li>
<li><em>complete solution</em>: …</li>
<li><em>human-readable solution:</em> …</li>
</ul>
</div>
<div id="what-is-the-most-prominent-location-outside-of-al-andalus-what-about-by-centuries" class="section level3 hasAnchor" number="5.2.13">
<h3><span class="header-section-number">5.2.13</span> [14] What is the most prominent location outside of al-Andalus? What about by centuries?<a href="data-manipulation-ii.html#what-is-the-most-prominent-location-outside-of-al-andalus-what-about-by-centuries" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<ul>
<li><em>algorithmic solution</em>: …</li>
<li><em>complete solution</em>: …</li>
<li><em>human-readable solution:</em> …</li>
</ul>
</div>
<div id="do-the-same-task-but-for-common-era-centuries." class="section level3 hasAnchor" number="5.2.14">
<h3><span class="header-section-number">5.2.14</span> [15] Do the same task, but for common era centuries.<a href="data-manipulation-ii.html#do-the-same-task-but-for-common-era-centuries." class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p><strong>Hint:</strong> you will also need to use a function from the previous lesson that converts AH dates to CE dates. Think carefully where you need to plug it in, i.e. between what steps.</p>
<ul>
<li><em>algorithmic solution</em>: …</li>
<li><em>complete solution</em>: …</li>
<li><em>human-readable solution:</em> …</li>
</ul>

</div>
</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="data-manipulation-i.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="control-flow-regular-expressions.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": true,
"facebook": true,
"twitter": true,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"whatsapp": false,
"all": ["facebook", "twitter", "github"]
},
"fontsettings": {
"theme": "white",
"family": "serif",
"size": 2
},
"edit": {
"link": "https://github.com/eis1600/hdis-audition-statements/edit/main/050-Class05.Rmd",
"text": "Edit"
},
"history": {
"link": null,
"text": null
},
"view": {
"link": "https://github.com/eis1600/hdis-audition-statements/blob/main/050-Class05.Rmd",
"text": null
},
"download": null,
"search": {
"engine": "fuse",
"options": null
},
"toc": {
"collapse": "section",
"scroll_highlight": true
},
"toolbar": {
"position": "fixed"
},
"info": true
});
});
</script>

</body>

</html>
